### ISSUE TITLE
Could not open admin settings after #1021

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1025]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.5.0-RC (7b5d741)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 74.0.3729.169|

How to reproduce? (再現手順)
---------------------------

0. Set `APP_SITE_URL` to `https://growi.example.com`, and `npm run server:dev`
1. Login to GROWI
2. Open admin settings

What happens? (症状)
---------------------

Got error:
```
TypeError: Cannot read property '4' of null
    at hasTrailingSlash (/opt/growi/node_modules/growi-commons/src/util/path-utils.js:67:16)
    at Object.addTrailingSlash (/opt/growi/node_modules/growi-commons/src/util/path-utils.js:98:8)
    at Object.swig.setFilter [as addTrailingSlash] (/opt/growi/src/server/util/middlewares.js:154:24)
    at Object.eval [as tpl] (eval at precompile (/opt/growi/node_modules/swig-templates/lib/swig.js:497:13), <anonymous>:54:828)
    at compiled (/opt/growi/node_modules/swig-templates/lib/swig.js:618:18)
    at Object.eval [as tpl] (eval at precompile (/opt/growi/node_modules/swig-templates/lib/swig.js:497:13), <anonymous>:194:123)
    at compiled (/opt/growi/node_modules/swig-templates/lib/swig.js:618:18)
    at /opt/growi/node_modules/swig-templates/lib/swig.js:558:20
    at /opt/growi/node_modules/swig-templates/lib/swig.js:689:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

What is the expected result? (期待される動作)
-------------------------------------------

- Get no error.

**Comment by yuki-takei** [comment]
fixed by #1026
