### ISSUE TITLE
Bug: couldn't attach file to new page

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1029]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | CentOS 7.6 |
|GROWI     |3.5.0-RC (d3a7702aaf542bc3f0deb259a2cfe0d414f83e97)|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes (Kubernetes)|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.5|
|browser   |Chrome 75.0.3770.80|

How to reproduce? (再現手順)
---------------------------

0. Configure GROWI to use S3
1. Access non existing page
1. Switch to create tab
1. Drag and drop file to upload

What happens? (症状)
---------------------

- After long waiting, I got an error in JS console: `ERROR: growi:PageEditor: failed to upload Error: Request failed with status code 504`

<details><summary>Error logs appeared in shell: (Click here to expand)</summary><div>

```
[2019-06-08T11:38:35.934Z]  INFO: express/60 on growi-7b864759c9-gx847: ::ffff:10.8.2.173 <-- POST /_api/attachments.add HTTP/1.1 200 - https://growi.example.com/no%20such%20page Chrome 75.0 Mac OS X 10.14.5 59995.156953 ms (req_id=06b61035-8496-467f-b8e9-ac42b924baf5)
[2019-06-08T11:38:38.674Z]  INFO: express/60 on growi-7b864759c9-gx847: ::ffff:10.8.2.173 <-- GET /_api/attachments.limit?fileSize=188766 HTTP/1.1 200 90 https://growi.example.com/no%20such%20page Chrome 75.0 Mac OS X 10.14.5 2.913325 ms (req_id=bd264c77-5ee8-4e25-a2f0-9ab1ae39347c)
[2019-06-08T11:38:40.326Z] ERROR: growi/60 on growi-7b864759c9-gx847:
  Unhandled Rejection: Promise: Promise {
    <rejected> { CastError: Cast to ObjectId failed for value "null" at path "_id" for model "Page"
        at new CastError (/opt/growi/node_modules/mongoose/lib/error/cast.js:29:11)
        at ObjectId.cast (/opt/growi/node_modules/mongoose/lib/schema/objectid.js:232:11)
        at ObjectId.SchemaType.applySetters (/opt/growi/node_modules/mongoose/lib/schematype.js:845:12)
        at ObjectId.SchemaType._castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1248:15)
        at ObjectId.SchemaType.castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1238:15)
        at ObjectId.SchemaType.castForQueryWrapper (/opt/growi/node_modules/mongoose/lib/schematype.js:1217:15)
        at cast (/opt/growi/node_modules/mongoose/lib/cast.js:307:32)
        at model.Query.Query.cast (/opt/growi/node_modules/mongoose/lib/query.js:4279:12)
        at model.Query.Query._castConditions (/opt/growi/node_modules/mongoose/lib/query.js:1725:10)
        at model.Query.<anonymous> (/opt/growi/node_modules/mongoose/lib/query.js:1976:8)
        at model.Query._wrappedThunk [as _findOne] (/opt/growi/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
        at process.nextTick (/opt/growi/node_modules/kareem/index.js:369:33)
        at process._tickCallback (internal/process/next_tick.js:61:11)
      message:
       'Cast to ObjectId failed for value "null" at path "_id" for model "Page"',
      name: 'CastError',
      stringValue: '"null"',
      kind: 'ObjectId',
      value: 'null',
      path: '_id',
      reason: undefined,
      model:
       { [Function: model]
         hooks: [Kareem],
         base: [Mongoose],
         modelName: 'Page',
         model: [Function: model],
         db: [NativeConnection],
         discriminators: undefined,
         events: [EventEmitter],
         '$appliedMethods': true,
         updateCommentCount: [Function],
         getGrantLabels: [Function],
         getUserPagePath: [Function],
         getDeletedPageName: [Function],
         getRevertDeletedPageName: [Function],
         isDeletableName: [Function],
         isCreatableName: [Function],
         fixToCreatableName: [Function],
         updateRevision: [Function],
         isAccessiblePageByViewer: [AsyncFunction],
         findByIdAndViewer: [AsyncFunction],
         findByPath: [Function],
         findByPathAndViewer: [AsyncFunction],
         findAncestorByPathAndViewer: [AsyncFunction],
         findByRedirectTo: [Function],
         findListWithDescendants: [AsyncFunction],
         findListByStartWith: [AsyncFunction],
         findListByCreator: [AsyncFunction],
         findListByPageIds: [AsyncFunction],
         addConditionToFilteringByViewerForList: [AsyncFunction: addConditionToFilteringByViewerForList],
         generateQueryToListByStartWith: [Function],
         generateQueryToListWithDescendants: [Function],
         findTemplate: [Function],
         getStreamOfFindAll: [Function],
         create: [AsyncFunction],
         updatePage: [AsyncFunction],
         applyScopesToDescendantsAsyncronously: [AsyncFunction],
         deletePage: [AsyncFunction],
         deletePageRecursively: [AsyncFunction],
         revertDeletedPage: [AsyncFunction],
         revertDeletedPageRecursively: [AsyncFunction],
         completelyDeletePage: [AsyncFunction],
         completelyDeletePageRecursively: [AsyncFunction],
         removeByPath: [Function],
         removeRedirectOriginPageByPath: [AsyncFunction],
         rename: [AsyncFunction],
         renameRecursively: [AsyncFunction],
         handlePrivatePagesForDeletedGroup: [AsyncFunction],
         publicizePage: [AsyncFunction],
         transferPageToGroup: [AsyncFunction],
         registerHackmdPage: [Function],
         syncRevisionToHackmd: [Function],
         updateHasDraftOnHackmd: [AsyncFunction],
         getHistories: [Function],
         addSlashOfEnd: [Function],
         allPageCount: [Function],
         GRANT_PUBLIC: 1,
         GRANT_RESTRICTED: 2,
         GRANT_SPECIFIED: 3,
         GRANT_OWNER: 4,
         GRANT_USER_GROUP: 5,
         PAGE_GRANT_ERROR: 1,
         PageQueryBuilder: [Function: PageQueryBuilder],
         '$appliedHooks': true,
         _middleware: [Kareem],
         schema: [Schema],
         collection: [NativeCollection],
         Query: [Function],
         '$__insertMany': [Function],
         '$init': [Promise],
         '$caught': true,
         [Symbol(mongoose#Model)]: true } } } Reason: { CastError: Cast to ObjectId failed for value "null" at path "_id" for model "Page"
      at new CastError (/opt/growi/node_modules/mongoose/lib/error/cast.js:29:11)
      at ObjectId.cast (/opt/growi/node_modules/mongoose/lib/schema/objectid.js:232:11)
      at ObjectId.SchemaType.applySetters (/opt/growi/node_modules/mongoose/lib/schematype.js:845:12)
      at ObjectId.SchemaType._castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1248:15)
      at ObjectId.SchemaType.castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1238:15)
      at ObjectId.SchemaType.castForQueryWrapper (/opt/growi/node_modules/mongoose/lib/schematype.js:1217:15)
      at cast (/opt/growi/node_modules/mongoose/lib/cast.js:307:32)
      at model.Query.Query.cast (/opt/growi/node_modules/mongoose/lib/query.js:4279:12)
      at model.Query.Query._castConditions (/opt/growi/node_modules/mongoose/lib/query.js:1725:10)
      at model.Query.<anonymous> (/opt/growi/node_modules/mongoose/lib/query.js:1976:8)
      at model.Query._wrappedThunk [as _findOne] (/opt/growi/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at process.nextTick (/opt/growi/node_modules/kareem/index.js:369:33)
      at process._tickCallback (internal/process/next_tick.js:61:11)
    message:
     'Cast to ObjectId failed for value "null" at path "_id" for model "Page"',
    name: 'CastError',
    stringValue: '"null"',
    kind: 'ObjectId',
    value: 'null',
    path: '_id',
    reason: undefined,
    model:
     { [Function: model]
       hooks: Kareem { _pres: [Map], _posts: [Map] },
       base:
        Mongoose {
          connections: [Array],
          models: [Object],
          modelSchemas: [Object],
          options: [Object],
          _pluralize: [Function: pluralize],
          Schema: [Function],
          model: [Function],
          plugins: [Array] },
       modelName: 'Page',
       model: [Function: model],
       db:
        NativeConnection {
          base: [Mongoose],
          collections: [Object],
          models: [Object],
          config: [Object],
          replica: false,
          options: null,
          otherDbs: [],
          relatedDbs: {},
          states: [Object],
          _readyState: 1,
          _closeCalled: false,
          _hasOpened: true,
          '$internalEmitter': [EventEmitter],
          _listening: false,
          _connectionOptions: [Object],
          name: 'growi',
          host: 'mongodb',
          port: 27017,
          user: undefined,
          pass: undefined,
          client: [MongoClient],
          '$initialConnection': [Promise],
          db: [Db] },
       discriminators: undefined,
       events:
        EventEmitter {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined },
       '$appliedMethods': true,
       updateCommentCount: [Function],
       getGrantLabels: [Function],
       getUserPagePath: [Function],
       getDeletedPageName: [Function],
       getRevertDeletedPageName: [Function],
       isDeletableName: [Function],
       isCreatableName: [Function],
       fixToCreatableName: [Function],
       updateRevision: [Function],
       isAccessiblePageByViewer: [AsyncFunction],
       findByIdAndViewer: [AsyncFunction],
       findByPath: [Function],
       findByPathAndViewer: [AsyncFunction],
       findAncestorByPathAndViewer: [AsyncFunction],
       findByRedirectTo: [Function],
       findListWithDescendants: [AsyncFunction],
       findListByStartWith: [AsyncFunction],
       findListByCreator: [AsyncFunction],
       findListByPageIds: [AsyncFunction],
       addConditionToFilteringByViewerForList: [AsyncFunction: addConditionToFilteringByViewerForList],
       generateQueryToListByStartWith: [Function],
       generateQueryToListWithDescendants: [Function],
       findTemplate: [Function],
       getStreamOfFindAll: [Function],
       create: [AsyncFunction],
       updatePage: [AsyncFunction],
       applyScopesToDescendantsAsyncronously: [AsyncFunction],
       deletePage: [AsyncFunction],
       deletePageRecursively: [AsyncFunction],
       revertDeletedPage: [AsyncFunction],
       revertDeletedPageRecursively: [AsyncFunction],
       completelyDeletePage: [AsyncFunction],
       completelyDeletePageRecursively: [AsyncFunction],
       removeByPath: [Function],
       removeRedirectOriginPageByPath: [AsyncFunction],
       rename: [AsyncFunction],
       renameRecursively: [AsyncFunction],
       handlePrivatePagesForDeletedGroup: [AsyncFunction],
       publicizePage: [AsyncFunction],
       transferPageToGroup: [AsyncFunction],
       registerHackmdPage: [Function],
       syncRevisionToHackmd: [Function],
       updateHasDraftOnHackmd: [AsyncFunction],
       getHistories: [Function],
       addSlashOfEnd: [Function],
       allPageCount: [Function],
       GRANT_PUBLIC: 1,
       GRANT_RESTRICTED: 2,
       GRANT_SPECIFIED: 3,
       GRANT_OWNER: 4,
       GRANT_USER_GROUP: 5,
       PAGE_GRANT_ERROR: 1,
       PageQueryBuilder: [Function: PageQueryBuilder],
       '$appliedHooks': true,
       _middleware: Kareem { _pres: [Map], _posts: [Map] },
       schema:
        Schema {
          obj: [Object],
          paths: [Object],
          aliases: {},
          subpaths: [Object],
          virtuals: [Object],
          singleNestedPaths: {},
          nested: {},
          inherits: {},
          callQueue: [],
          _indexes: [],
          methods: [Object],
          methodOptions: {},
          statics: [Object],
          tree: [Object],
          query: {},
          childSchemas: [],
          plugins: [Array],
          '$id': 1,
          s: [Object],
          _userProvidedOptions: [Object],
          options: [Object],
          '$globalPluginsApplied': true,
          _requiredpaths: [Array],
          _indexedpaths: [Array] },
       collection:
        NativeCollection {
          collection: [Collection],
          opts: [Object],
          name: 'pages',
          collectionName: 'pages',
          conn: [NativeConnection],
          queue: [],
          buffer: false,
          emitter: [EventEmitter] },
       Query: { [Function] base: [Query] },
       '$__insertMany': [Function],
       '$init': Promise { [Circular] },
       '$caught': true,
       [Symbol(mongoose#Model)]: true } }
```

</div></details>

What is the expected result? (期待される動作)
-------------------------------------------

- Got no error.

Note
----

- I could attach files to existing pages without problem.

**Comment by yuki-takei** [comment]
@shield-9 Thank you for your report. I have confirmed it was reproduced. I'll fix this soon.
