### ISSUE TITLE
Improvement: Rebuild search index without outage

### ISSUE THREAD

**Issue by shield-9** [weseek/growi#1162]
Elasticsearchのindexをリビルドしている最中、一時的に検索結果が欠損した状態になってしまい、ページ数が多いほどこの状態が長く続いてしまいます。

これを解決するために、ElasticsearchのIndex Aliasesを使って、新しいIndexができるまでは古いものを使い続けるという処理が実現できると、管理者は気軽にリビルドを実行できるようになりますし、利用者はそれを気にすることなく検索機能を使えるようになります。

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

**Comment by yuki-takei** [comment]
@shield-9
アイデアありがとうございます。簡単にできそうなので近日中に実装しようと思います。しばらくお待ちください。

**Comment by yuki-takei** [comment]
fixed by #1183 

@shield-9 
実装完了し、master ブランチにマージされました。
こちらでもこれから社内の環境でテストしてみる予定ですが、もし master branch 版試用のお時間がありましたらフィードバックいただけると助かります。

**Comment by shield-9** [comment]
@yuki-takei こちらで触ってみたところ、検索機能のダウンタイムをなくすことができていることが確認できました！

ただ、ビルドが完了する前にもう一度Build Nowをクリックしてしまうと、ログに以下のエラーが出ました。
```
[2019-09-12T04:23:58.792Z]  INFO: growi:lib:search/58 on growi-search-test: addAllPages add anyway (items, errors, took):  910 true 29300 ms
[2019-09-12T04:23:58.845Z] ERROR: growi/58 on growi-search-test:
  Unhandled Rejection: Promise: Promise {                                                                                                                                                                                                         Rejection: Promise: Promise {                                                                                                                                                                                                           <rejected> { Error: [resource_already_exists_exception] index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists, with { index_uuid="aXhwFkOMT0q9J_MLxisICQ" & index="growi-tmp" }
        at respond (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:315:15)
        at checkRespForFailure (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:274:7)
        at HttpConnector.<anonymous> (/opt/growi/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
        at IncomingMessage.wrapper (/opt/growi/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
      status: 400,
      displayName: 'BadRequest',
      message:
       '[resource_already_exists_exception] index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists, with { index_uuid="aXhwFkOMT0q9J_MLxisICQ" & index="growi-tmp" }',
      path: '/growi-tmp',
      query: {},
      body: { error: [Object], status: 400 },
      statusCode: 400,
      response:
       '{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists","index_uuid":"aXhwFkOMT0q9J_MLxisICQ","index":"growi-tmp"}],"type":"resource_already_exists_exception","reason":"index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists","index_uuid":"aXhwFkOMT0q9J_MLxisICQ","index":"growi-tmp"},"status":400}',
      toString: [Function],
      toJSON: [Function] } } Reason: { Error: [resource_already_exists_exception] index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists, with { index_uuid="aXhwFkOMT0q9J_MLxisICQ" & index="growi-tmp" }
      at respond (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:315:15)
      at checkRespForFailure (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:274:7)
      at HttpConnector.<anonymous> (/opt/growi/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
      at IncomingMessage.wrapper (/opt/growi/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
    status: 400,
    displayName: 'BadRequest',
    message:
     '[resource_already_exists_exception] index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists, with { index_uuid="aXhwFkOMT0q9J_MLxisICQ" & index="growi-tmp" }',
    path: '/growi-tmp',
    query: {},
    body:
     { error:
        { root_cause: [Array],
          type: 'resource_already_exists_exception',
          reason: 'index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists',
          index_uuid: 'aXhwFkOMT0q9J_MLxisICQ',
          index: 'growi-tmp' },
       status: 400 },
    statusCode: 400,
    response:
     '{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists","index_uuid":"aXhwFkOMT0q9J_MLxisICQ","index":"growi-tmp"}],"type":"resource_already_exists_exception","reason":"index [growi-tmp/aXhwFkOMT0q9J_MLxisICQ] already exists","index_uuid":"aXhwFkOMT0q9J_MLxisICQ","index":"growi-tmp"},"status":400}',
    toString: [Function],
    toJSON: [Function] }
[2019-09-12T04:24:12.320Z]  INFO: express/58 on growi-search-test: ::ffff:10.8.2.84 <-- POST /_api/admin/search/build HTTP/1.1 200 11 https://wiki.example.com/admin/search Chrome 76.0 Windows 10.0.0 13727.791805 ms (req_id=209e1670-9af5-415b-8cd7-2b60f04bd8b3)
[2019-09-12T04:24:12.408Z]  INFO: growi:lib:search/58 on growi-search-test: addAllPages add anyway (items, errors, took):  2000 false 4548 ms
[2019-09-12T04:24:13.201Z]  INFO: growi:lib:search/58 on growi-search-test: addAllPages add anyway (items, errors, took):  910 false 1703 ms
[2019-09-12T04:24:58.745Z]  INFO: express/58 on growi-search-test: 127.0.0.1 <-- POST /_api/admin/search/build HTTP/1.1 200 - https://wiki.example.com/admin/search Chrome 76.0 Windows 10.0.0 60001.014707 ms (req_id=e15bba7f-2693-4f3c-b329-da8d6158ec7c)
```
手動で何度か試した範囲内では、特に検索結果の表示に影響が出ることはなさそうでしたが、もしほかの方から影響が出るという報告が出てくるようであれば、mutexの仕組みが必要かもしれないです。
