### ISSUE TITLE
herokuデプロイ環境にて、インデックスのリビルドに失敗する

### ISSUE THREAD

**Issue by mshowta** [weseek/growi#1282]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |heroku|
|GROWI     |3.5.17-RC|
|node.js   |10.16.3|
|npm       |6.12.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |win10|
|browser   |google crome 77.0.3865.120|

How to reproduce? (再現手順)
---------------------------

1. herokuにてデプロイ
1. 管理画面から全文検索管理
1. インデックスのリビルドボタン押す

What happens? (症状)
---------------------

- GUI上反応がない。
- Application Logsに下記が出力、timeoutしている(ように見える)

```

2019-10-18T00:58:06.65131+00:00 app[web.1]: [90m[2019-10-18T00:58:06.647Z][39m [31mERROR[39m: growi/66 on 767ebe9d-e990-4de8-8e4b-ec55152ba2dc:
2019-10-18T00:58:06.651322+00:00 app[web.1]: [90m  [36mUnhandled Rejection: Promise: Promise {
2019-10-18T00:58:06.65133+00:00 app[web.1]:     <rejected> { Error: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]
2019-10-18T00:58:06.651333+00:00 app[web.1]:         at respond (/app/node_modules/elasticsearch/src/lib/transport.js:315:15)
2019-10-18T00:58:06.651335+00:00 app[web.1]:         at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:274:7)
2019-10-18T00:58:06.651337+00:00 app[web.1]:         at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
2019-10-18T00:58:06.65134+00:00 app[web.1]:         at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
2019-10-18T00:58:06.651342+00:00 app[web.1]:         at IncomingMessage.emit (events.js:203:15)
2019-10-18T00:58:06.651343+00:00 app[web.1]:         at endReadableNT (_stream_readable.js:1145:12)
2019-10-18T00:58:06.651346+00:00 app[web.1]:         at process._tickCallback (internal/process/next_tick.js:63:19)
2019-10-18T00:58:06.651348+00:00 app[web.1]:       status: 400,
2019-10-18T00:58:06.65135+00:00 app[web.1]:       displayName: 'BadRequest',
2019-10-18T00:58:06.651353+00:00 app[web.1]:       message:
2019-10-18T00:58:06.651379+00:00 app[web.1]:        '[mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]',
2019-10-18T00:58:06.651382+00:00 app[web.1]:       path: '/crowi',
2019-10-18T00:58:06.651384+00:00 app[web.1]:       query: {},
2019-10-18T00:58:06.651385+00:00 app[web.1]:       body: { error: [Object], status: 400 },
2019-10-18T00:58:06.651387+00:00 app[web.1]:       statusCode: 400,
2019-10-18T00:58:06.651388+00:00 app[web.1]:       response:
2019-10-18T00:58:06.6514+00:00 app[web.1]:        '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]"}},"status":400}',
2019-10-18T00:58:06.651401+00:00 app[web.1]:       toString: [Function],
2019-10-18T00:58:06.651405+00:00 app[web.1]:       toJSON: [Function] } } Reason: { Error: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]
2019-10-18T00:58:06.651407+00:00 app[web.1]:       at respond (/app/node_modules/elasticsearch/src/lib/transport.js:315:15)
2019-10-18T00:58:06.651408+00:00 app[web.1]:       at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:274:7)
2019-10-18T00:58:06.65141+00:00 app[web.1]:       at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
2019-10-18T00:58:06.651412+00:00 app[web.1]:       at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
2019-10-18T00:58:06.651413+00:00 app[web.1]:       at IncomingMessage.emit (events.js:203:15)
2019-10-18T00:58:06.651415+00:00 app[web.1]:       at endReadableNT (_stream_readable.js:1145:12)
2019-10-18T00:58:06.651416+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:63:19)
2019-10-18T00:58:06.651418+00:00 app[web.1]:     status: 400,
2019-10-18T00:58:06.651419+00:00 app[web.1]:     displayName: 'BadRequest',
2019-10-18T00:58:06.651421+00:00 app[web.1]:     message:
2019-10-18T00:58:06.651425+00:00 app[web.1]:      '[mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]',
2019-10-18T00:58:06.651427+00:00 app[web.1]:     path: '/crowi',
2019-10-18T00:58:06.651428+00:00 app[web.1]:     query: {},
2019-10-18T00:58:06.65143+00:00 app[web.1]:     body:
2019-10-18T00:58:06.651431+00:00 app[web.1]:      { error:
2019-10-18T00:58:06.651433+00:00 app[web.1]:         { root_cause: [Array],
2019-10-18T00:58:06.651434+00:00 app[web.1]:           type: 'mapper_parsing_exception',
2019-10-18T00:58:06.651436+00:00 app[web.1]:           reason:
2019-10-18T00:58:06.651437+00:00 app[web.1]:            'Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]',
2019-10-18T00:58:06.651439+00:00 app[web.1]:           caused_by: [Object] },
2019-10-18T00:58:06.65144+00:00 app[web.1]:        status: 400 },
2019-10-18T00:58:06.651442+00:00 app[web.1]:     statusCode: 400,
2019-10-18T00:58:06.651443+00:00 app[web.1]:     response:
2019-10-18T00:58:06.651445+00:00 app[web.1]:      '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]"}},"status":400}',
2019-10-18T00:58:06.651446+00:00 app[web.1]:     toString: [Function],
2019-10-18T00:58:06.651448+00:00 app[web.1]:     toJSON: [Function] }[39m
2019-10-18T00:58:16.924109+00:00 heroku[web.1]: source=web.1 dyno=heroku.149905747.767ebe9d-e990-4de8-8e4b-ec55152ba2dc sample#load_avg_1m=0.00 sample#load_avg_5m=0.00 sample#load_avg_15m=0.00
2019-10-18T00:58:16.950019+00:00 heroku[web.1]: source=web.1 dyno=heroku.149905747.767ebe9d-e990-4de8-8e4b-ec55152ba2dc sample#memory_total=121.45MB sample#memory_rss=118.59MB sample#memory_cache=2.86MB sample#memory_swap=0.00MB sample#memory_pgpgin=110134pages sample#memory_pgpgout=81087pages sample#memory_quota=512.00MB
2019-10-18T00:58:36.69682+00:00 heroku[web.1]: source=web.1 dyno=heroku.149905747.767ebe9d-e990-4de8-8e4b-ec55152ba2dc sample#load_avg_1m=0.00 sample#load_avg_5m=0.00 sample#load_avg_15m=0.00
2019-10-18T00:58:36.726754+00:00 heroku[web.1]: source=web.1 dyno=heroku.149905747.767ebe9d-e990-4de8-8e4b-ec55152ba2dc sample#memory_total=121.59MB sample#memory_rss=118.73MB sample#memory_cache=2.86MB sample#memory_swap=0.00MB sample#memory_pgpgin=110169pages sample#memory_pgpgout=81087pages sample#memory_quota=512.00MB
2019-10-18T00:58:36.594652+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/_api/admin/search/build" host=example.herokuapp.com request_id=ba5f0588-6931-45a3-b6f0-e8dee8346ebf fwd="153.156.76.27" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
2019-10-18T00:58:36.596193+00:00 app[web.1]: [39m[90m[2019-10-18T00:58:36.595Z][39m [32m INFO[39m: express/66 on 767ebe9d-e990-4de8-8e4b-ec55152ba2dc: [36m127.0.0.1 <-- POST /_api/admin/search/build HTTP/1.1 200 - https://example.herokuapp.com/admin/search Chrome 77.0 Windows 10.0.0 29994.374007 ms[39m[90m (req_id=7edf1490-d9be-4d9a-a604-fc66c39c5e72)[39m
```

What is the expected result? (期待される動作)
-------------------------------------------

- リビルドの完了メッセージが出力される。

Note
----

- 初めて利用します。前提条件に不備などありましたらご指摘下さい。

**Comment by shield-9** [comment]
Elasticsearchのバージョンって、何をお使いですか？

このエラーは7.x系を使ったときに発生するもののようにも見えます。

**Comment by mshowta** [comment]
ご確認ありがとうございます。Elasticsearchはbonsaiを使っています。

特に指定はしていないですが、OverviewからDetailを確認すると
Elasticsearch 7.2.0  を使っいるようです。

**Comment by shield-9** [comment]
まず、Heroku上かどうかにかかわらず、ES 6.x系のみが推奨環境なので、ソースを改変する以外に7.x系を使う方法は、現状だとありません。

----

https://github.com/weseek/growi/blob/v3.5.16/app.json#L39
ES 6.5.4で起動するように指定されていますが、[Bonsai側のドキュメント](https://docs.bonsai.io/article/139-which-versions-bonsai-supports)を見ると、本日時点では、7.2.0以外を利用するためには、別途課金が必要な仕様となっているようです。

なので、選択肢としては、Heroku以外の環境で使うか、Elasticsearch 7.xへの対応を待つか、自力で対応させるかの3通りになるのかなと思います。

**Comment by mshowta** [comment]
ありがとうございます！
対応、前提条件の確認方法についても理解できました！

**Comment by yuki-takei** [comment]
Bonsai が 6.x しか使えないということで、[Searchbox](https://elements.heroku.com/addons/searchbox) を使って対応を試みています。

[support/use-searchbox-on-heroku](https://github.com/weseek/growi/tree/support/use-searchbox-on-heroku) ブランチで試していますが、まだうまく動いていないです。Application Logs 未確認。引き続き調査します。

**Comment by yuki-takei** [comment]
https://devcenter.heroku.com/articles/searchbox#installing-the-add-on

```
$ heroku config | grep SEARCHBOX_URL
SEARCHBOX_URL  => https://paas:8ed0986ecaabcb7c20b4b2bdd6251f2d@.....searchly.com
```
とのことなので、Bonsai と違って index 名は GROWI 側で指定する必要がありあそう。

**Comment by yuki-takei** [comment]
```
2019-10-19T15:44:01.973274+00:00 app[web.1]: [2019-10-19T15:44:01.973Z] ERROR: growi:lib:search/66 on 7b3a9652-7429-4172-bc73-30c52035a29f:
2019-10-19T15:44:01.973278+00:00 app[web.1]:   es check version error: Error: no nodes info
2019-10-19T15:44:01.97328+00:00 app[web.1]: at SearchClient.checkESVersion (/app/src/server/util/search.js:75:13)
2019-10-19T15:44:01.973281+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-10-19T15:44:01.94007+00:00 heroku[router]: at=info method=POST path="/_api/admin/search/build" host=use-searchbox-on-heroku.herokuapp.com request_id=b7ca97f7-b28f-4156-99e5-754f5e9130ee fwd="61.204.247.131" dyno=web.1 connect=1ms service=15ms status=200 bytes=628 protocol=https
2019-10-19T15:44:02.361214+00:00 app[web.1]: [2019-10-19T15:44:02.360Z] ERROR: growi/66 on 7b3a9652-7429-4172-bc73-30c52035a29f:
2019-10-19T15:44:02.361221+00:00 app[web.1]:   Unhandled Rejection: Promise: Promise {
2019-10-19T15:44:02.361225+00:00 app[web.1]: <rejected> { Error: Authentication Exception
2019-10-19T15:44:02.361226+00:00 app[web.1]: at respond (/app/node_modules/elasticsearch/src/lib/transport.js:315:15)
2019-10-19T15:44:02.361228+00:00 app[web.1]: at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:274:7)
2019-10-19T15:44:02.36123+00:00 app[web.1]: at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
2019-10-19T15:44:02.361231+00:00 app[web.1]: at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
2019-10-19T15:44:02.361233+00:00 app[web.1]: at IncomingMessage.emit (events.js:203:15)
2019-10-19T15:44:02.361234+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1145:12)
2019-10-19T15:44:02.361236+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:63:19)
2019-10-19T15:44:02.361238+00:00 app[web.1]: status: 401,
2019-10-19T15:44:02.36124+00:00 app[web.1]: displayName: 'AuthenticationException',
2019-10-19T15:44:02.361242+00:00 app[web.1]: message: 'Authentication Exception',
2019-10-19T15:44:02.361243+00:00 app[web.1]: path: '/_reindex',
2019-10-19T15:44:02.361245+00:00 app[web.1]: query: { wait_for_completion: false },
2019-10-19T15:44:02.361247+00:00 app[web.1]: body:
2019-10-19T15:44:02.361248+00:00 app[web.1]: { error_id: '0eb5241c-fd42-4c63-b293-68a4f5b57eab',
2019-10-19T15:44:02.36125+00:00 app[web.1]: errors: [Array] },
2019-10-19T15:44:02.361251+00:00 app[web.1]: statusCode: 401,
2019-10-19T15:44:02.361253+00:00 app[web.1]: response:
2019-10-19T15:44:02.361254+00:00 app[web.1]: '{"error_id":"0eb5241c-fd42-4c63-b293-68a4f5b57eab","errors":[{"code":90,"message":"Unauthorized access"}]}',
2019-10-19T15:44:02.361256+00:00 app[web.1]: toString: [Function],
2019-10-19T15:44:02.361257+00:00 app[web.1]: toJSON: [Function] } } Reason: { Error: Authentication Exception
2019-10-19T15:44:02.361259+00:00 app[web.1]: at respond (/app/node_modules/elasticsearch/src/lib/transport.js:315:15)
2019-10-19T15:44:02.36126+00:00 app[web.1]: at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:274:7)
2019-10-19T15:44:02.361262+00:00 app[web.1]: at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
2019-10-19T15:44:02.361263+00:00 app[web.1]: at IncomingMessage.wrapper (/app/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
2019-10-19T15:44:02.361265+00:00 app[web.1]: at IncomingMessage.emit (events.js:203:15)
2019-10-19T15:44:02.361266+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1145:12)
2019-10-19T15:44:02.361268+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:63:19)
2019-10-19T15:44:02.361269+00:00 app[web.1]: status: 401,
2019-10-19T15:44:02.361271+00:00 app[web.1]: displayName: 'AuthenticationException',
2019-10-19T15:44:02.361274+00:00 app[web.1]: message: 'Authentication Exception',
2019-10-19T15:44:02.361275+00:00 app[web.1]: path: '/_reindex',
2019-10-19T15:44:02.361277+00:00 app[web.1]: query: { wait_for_completion: false },
2019-10-19T15:44:02.361278+00:00 app[web.1]: body:
2019-10-19T15:44:02.36128+00:00 app[web.1]: { error_id: '0eb5241c-fd42-4c63-b293-68a4f5b57eab',
2019-10-19T15:44:02.361281+00:00 app[web.1]: errors: [ [Object] ] },
2019-10-19T15:44:02.361283+00:00 app[web.1]: statusCode: 401,
2019-10-19T15:44:02.361284+00:00 app[web.1]: response:
2019-10-19T15:44:02.361286+00:00 app[web.1]: '{"error_id":"0eb5241c-fd42-4c63-b293-68a4f5b57eab","errors":[{"code":90,"message":"Unauthorized access"}]}',
2019-10-19T15:44:02.361287+00:00 app[web.1]: toString: [Function],
2019-10-19T15:44:02.361289+00:00 app[web.1]: toJSON: [Function] }
```

**Comment by Sabazo** [comment]
https://devcenter.heroku.com/articles/searchbox#installing-the-add-on

ELASTICSEARCH_URIのポートを9200から443に変更すると動きましたよ。

**Comment by yuki-takei** [comment]
@Sabazo 正常動作確認しました！垂れ込み感謝です。

それから上で出ていた Authentication Exception は、reindex 操作の権限がないが故のものだったことが判明。Searchbox 利用時は reindex や alias 付け替え機能を無効化して対応します。

**Comment by yuki-takei** [comment]
Searchbox 対応完了しました。v3.5.19 リリースをお待ちください。
