### ISSUE TITLE
Workaround: Avoid "Can't resolve 'react-node-resolver'" error when deploying to HEROKU

### ISSUE THREAD

**Issue by you-at4** [weseek/growi#1502]
Environment
------------

### Host
heroku

How to reproduce? (再現手順)
---------------------------

1. growiのトップにある「Deploy to Heroku」をクリック
1. 適当なApp Nameをつけて、デフォルト設定のままDeploy App

What happens? (症状)
---------------------

1. Build app で以下のログが出たまま進まなくなる

````
    -----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=development
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=10.17.0 <13
       engines.npm (package.json):   >=6.11.3 <7
       engines.yarn (package.json):  >=1.19.1 <2
       
       Resolving node version >=10.17.0 <13...
       Downloading and installing node 12.14.0...
       Bootstrapping npm >=6.11.3 <7 (replacing 6.13.4)...
       npm >=6.11.3 <7 installed
       Resolving yarn version >=1.19.1 <2...
       Downloading and installing yarn (1.21.1)...
       Installed yarn 1.21.1
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.21.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning sha.js@2.4.9: Invalid bin entry for "sha.js" (in "sha.js").
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       info fsevents@1.2.4: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > mongoose-gridfs@1.2.2" has incorrect peer dependency "mongoose@>=5.5.14".
       warning "mongoose-gridfs > @lykmapipo/mongoose-common@0.25.3" has incorrect peer dependency "mongoose@>=5.6.0".
       warning "mongoose-gridfs > @lykmapipo/mongoose-common > mongoose-valid8@1.5.9" has incorrect peer dependency "mongoose@>=5.6.0".
       warning " > multer-autoreap@1.0.3" has incorrect peer dependency "express@^4.16.3".
       warning "eslint-config-weseek > eslint-config-airbnb@17.1.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".
       warning "eslint-config-weseek > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.1.1".
       warning "eslint-config-weseek > eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".
       warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
       warning " > metismenu@3.0.3" has unmet peer dependency "jquery@^3.3.1".
       warning " > react-frame-component@4.0.0" has unmet peer dependency "prop-types@^15.5.9".
       warning " > stylelint-config-recess-order@2.0.1" has unmet peer dependency "stylelint@^9.9.0".
       warning "stylelint-config-recess-order > stylelint-order@2.1.0" has unmet peer dependency "stylelint@^9.10.1".
       warning "swagger2openapi > better-ajv-errors@0.6.6" has unmet peer dependency "ajv@4.11.8 - 6".
       warning "unstated > create-react-context@0.1.6" has unmet peer dependency "prop-types@^15.0.0".
       [4/4] Building fresh packages...
       Done in 127.74s.
       
-----> Build
       Detected both "build" and "heroku-postbuild" scripts
       Running heroku-postbuild (yarn)
       yarn run v1.21.1
       $ sh bin/heroku/install-packages.sh && npm run build:prod
       [1/5] Validating package.json...
       [2/5] Resolving packages...
       [3/5] Fetching packages...
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       info fsevents@1.2.4: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
       [4/5] Linking dependencies...
warning " > mongoose-gridfs@1.2.2" has incorrect peer dependency "mongoose@>=5.5.14".
warning "mongoose-gridfs > @lykmapipo/mongoose-common@0.25.3" has incorrect peer dependency "mongoose@>=5.6.0".
warning "mongoose-gridfs > @lykmapipo/mongoose-common > mongoose-valid8@1.5.9" has incorrect peer dependency "mongoose@>=5.6.0".
warning " > multer-autoreap@1.0.3" has incorrect peer dependency "express@^4.16.3".
warning "eslint-config-weseek > eslint-config-airbnb@17.1.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "eslint-config-weseek > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.1.1".
warning "eslint-config-weseek > eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > metismenu@3.0.3" has unmet peer dependency "jquery@^3.3.1".
warning " > react-frame-component@4.0.0" has unmet peer dependency "prop-types@^15.5.9".
warning " > stylelint-config-recess-order@2.0.1" has unmet peer dependency "stylelint@^9.9.0".
warning "stylelint-config-recess-order > stylelint-order@2.1.0" has unmet peer dependency "stylelint@^9.10.1".
warning "swagger2openapi > better-ajv-errors@0.6.6" has unmet peer dependency "ajv@4.11.8 - 6".
warning "unstated > create-react-context@0.1.6" has unmet peer dependency "prop-types@^15.0.0".
warning "react-images > react-view-pager@0.6.0" has unmet peer dependency "prop-types@^15.5.8".
warning "react-images > react-full-screen@0.2.4" has unmet peer dependency "prop-types@^15.5".
warning " > growi-plugin-attachment-refs@1.0.6" has incorrect peer dependency "react-images@~1.0.0".
warning " > react-images@1.1.0-beta.0" has unmet peer dependency "prop-types@^15.7.2".
       [5/5] Building fresh packages...
       success Saved lockfile.
       success Saved 25 new dependencies.
       info Direct dependencies
       ├─ growi-plugin-attachment-refs@1.0.6
       ├─ growi-plugin-lsx@3.0.7
       ├─ growi-plugin-pukiwiki-like-linker@3.0.1
       ├─ react-images@1.1.0-beta.0
       └─ react-motion@0.5.2
       info All dependencies
       ├─ @types/prop-types@15.7.3
       ├─ @types/react@16.9.17
       ├─ a11y-focus-store@1.0.0
       ├─ animation-bus@0.2.0
       ├─ bowser@1.9.4
       ├─ css-in-js-utils@2.0.1
       ├─ csstype@2.6.8
       ├─ exenv@1.2.2
       ├─ fscreen@1.0.2
       ├─ get-prefix@1.0.0
       ├─ glam@5.0.1
       ├─ growi-plugin-attachment-refs@1.0.6
       ├─ growi-plugin-lsx@3.0.7
       ├─ growi-plugin-pukiwiki-like-linker@3.0.1
       ├─ hyphenate-style-name@1.0.3
       ├─ inline-style-prefixer@3.0.8
       ├─ raf-schd@2.1.2
       ├─ react-full-screen@0.2.4
       ├─ react-images@1.1.0-beta.0
       ├─ react-lifecycles-compat@3.0.4
       ├─ react-motion@0.5.2
       ├─ react-scrolllock@4.0.1
       ├─ react-view-pager@0.6.0
       ├─ resize-observer-polyfill@1.5.0
       └─ tabbable@1.1.2
       
       > growi@3.6.3-RC prebuild:prod /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > npm run clean && env-cmd -f config/env.prod.js npm run plugin:def && env-cmd -f config/env.prod.js npm run resource
       
       
       > growi@3.6.3-RC clean /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > npm-run-all -p clean:*
       
       
       > growi@3.6.3-RC clean:app /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > rimraf -- public/js public/styles
       
       
       > growi@3.6.3-RC clean:report /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > rimraf -- report
       
       
       > growi@3.6.3-RC plugin:def /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > node bin/generate-plugin-definitions-source.js
       
       [2019-12-23T07:40:47.535Z]  INFO: growi:bin:generate-plugin-definitions-source/5372 on f9d130cd-7e69-4976-b7c7-eb7502ce6d6d:
         Detected plugins:  [
           'growi-plugin-attachment-refs',
           'growi-plugin-lsx',
           'growi-plugin-pukiwiki-like-linker'
         ]
       
       > growi@3.6.3-RC resource /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > node bin/download-cdn-resources.js
       
       [2019-12-23T07:40:48.116Z]  INFO: growi:bin:download-cdn-resources/5414 on f9d130cd-7e69-4976-b7c7-eb7502ce6d6d: Using CDN. No resources are downloaded.
       
       > growi@3.6.3-RC build:prod /tmp/build_bf18d6f0fc477ea13029adb527b05f9e
       > env-cmd -f config/env.prod.js webpack --config config/webpack.prod.js --profile --bail
       
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
[hardsource:6bff10c2] Writing new cache 6bff10c2...
[hardsource:6bff10c2] Tracking node dependencies with: yarn.lock.
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-node-resolver' in '/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-scrolllock/dist'
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/webpack/lib/Compilation.js:888:10
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/hard-source-webpack-plugin/lib/TransformNormalModuleFactoryPlugin.js:121:26
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/neo-async/async.js:2830:7
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/neo-async/async.js:6877:13
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at callback (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/hard-source-webpack-plugin/lib/CacheEnhancedResolve.js:333:13)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:390:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:402:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
resolve 'react-node-resolver' in '/tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-scrolllock/dist'
  Parsed request is a module
  using description file: /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-scrolllock/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules
        using description file: /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/package.json (relative path: ./node_modules/react-node-resolver)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-node-resolver doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-node-resolver.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-node-resolver.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-node-resolver.json doesn't exist
            as directory
              /tmp/build_bf18d6f0fc477ea13029adb527b05f9e/node_modules/react-node-resolver doesn't exist
````

2. 以前のversionのHerokuでDeploy済みのgrowiを更新しようとしても同様なログが出て止まる

What is the expected result? (期待される動作)
-------------------------------------------

- 正常にDeployできる

**Comment by yuki-takei** [comment]
@you-at4
こちらの問題ですが、インストールしている react-images パッケージのバージョンが最新だと `react-images@1.1.0-beta.0` になってしまい、そちらだとうまく動かないようです。(まだ beta らしいので、そのバージョンで動かすことができるのかの調査はしていない)

ワークアラウンドとしては `react-images@1.0.0` を使えば解消しますので、起動時の `ADDITIONAL_PACKAGES` の入力で `react-images` を `react-images@1.0.0` としてください。

**Comment by yuki-takei** [comment]
master ブランチはこれから直しておきます。

**Comment by you-at4** [comment]
ADDITIONAL_PACKAGESを変更した所、新規にDeployも既存のGrowiの更新もできました。
ありがとうございます。
