### ISSUE TITLE
LDAP認証でのログイン失敗時にInternal Server Errorが発生する

### ISSUE THREAD

**Issue by shisyamo** [weseek/growi#1625]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS8|
|GROWI     |3.6.6|
|node.js   |12.14.1|
|npm       |6.13.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |chrome or firefox 72.0.2|

How to reproduce? (再現手順)
---------------------------
1. ログイン画面（LDAP認証時）でログインID、パスワードに誤ったものを指定する。

What happens? (症状)
---------------------

- ブラウザに真っ白なページが表示され、「Internal Server Error」の文字のみが表示され、再度ログインID、パスワードを入力することができなくなってしまう。ブラウザでリロードすればログイン画面が表示されますが。

What is the expected result? (期待される動作)
-------------------------------------------

- ログイン画面で「Sign in failure.」が出力され再度、入力を促す。

**Comment by yuki-takei** [comment]
@shisyamo こちらの Issue の再現手順ですが、再現させることができていません。

## こちらで試した再現手順
1. LDAP 認証が通る正常ログイン確認済みのユーザーを用意
1. ログアウト
1. 誤ったパスワードでログイン

上記で、期待される動作を満たしています。

## ログ表示について
ご報告いただいている症状では Internal Server Error が出ているとのことですので、サーバー側ログをいただけないでしょうか。

可能であれば、環境変数に以下を設定していただきたいです。
`DEBUG=growi:routes:login-passport,growi:service:PassportService`

## ログイン失敗時に想定されるサーバー側ログ

```
GET /login 200 15.593 ms - 15950
21:18:39.959Z DEBUG growi:routes:login-passport: --- authenticate with LocalStrategy ---
21:18:39.960Z DEBUG growi:routes:login-passport: user false
21:18:39.961Z DEBUG growi:routes:login-passport: info { message: 'Incorrect credentials.' }
21:18:39.961Z DEBUG growi:service:PassportService:
  ldap configuration:  {
    usernameField: 'loginForm[username]',
    passwordField: 'loginForm[password]',
    server: {
      url: 'ldaps://my.ldap.example.com',
      bindDN: 'uid=yuki,ou=people,dc=example,dc=com',
      bindCredentials: 'dummy password',
      searchBase: 'ou=people,dc=example,dc=com',
      searchFilter: '(|(uid={{username}})(mail={{username}}))',
      attrMapUsername: 'uid',
      attrMapName: ''
    },
    passReqToCallback: true
  }
21:18:40.009Z DEBUG growi:routes:login-passport: --- authenticate with ldapauth strategy ---
21:18:40.012Z DEBUG growi:routes:login-passport: response false
21:18:40.014Z DEBUG growi:routes:login-passport: info { message: 'Invalid username/password' }
POST /login 302 58.540 ms - 56
GET /login 200 27.291 ms - 16060
```

**Comment by shisyamo** [comment]
アドバイスありがとうございます。

環境変数を仕込みログを出力させてみました。

```
xpress-validator: requires to express-validator/check are deprecated.You should just use require("express-validator") instead.
(node:74) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
[2020-03-02T00:40:43.346Z]  INFO: growi:service:search/74 on df0324d7ed2d: Initializing search delegator
[2020-03-02T00:40:43.347Z]  INFO: growi:service:search/74 on df0324d7ed2d: Elasticsearch (not Searchbox) is enabled
[2020-03-02T00:40:50.175Z]  INFO: growi:plugins:PluginService/74 on df0324d7ed2d: load plugin 'growi-plugin-attachment-refs'
[2020-03-02T00:40:50.186Z]  INFO: growi:plugins:PluginService/74 on df0324d7ed2d: load plugin 'growi-plugin-lsx'
[2020-03-02T00:40:50.199Z]  INFO: growi:plugins:PluginService/74 on df0324d7ed2d: load plugin 'growi-plugin-pukiwiki-like-linker'
express-validator: requires to express-validator/filter are deprecated.You should just use require("express-validator") instead.
[2020-03-02T00:40:51.063Z]  INFO: growi:crowi/74 on df0324d7ed2d: [production] Express server is listening on port 3000
[2020-03-02T00:40:51.066Z] ERROR: growi/74 on df0324d7ed2d:
  Unhandled Rejection: Promise: Promise {
    <rejected> StatusCodeError: Request Timeout after 5000ms
        at /opt/growi/node_modules/elasticsearch/src/lib/transport.js:362:15
        at Timeout.<anonymous> (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:391:7)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      status: undefined,
      displayName: 'RequestTimeout',
      message: 'Request Timeout after 5000ms',
      body: false
    }
  } Reason: StatusCodeError: Request Timeout after 5000ms
      at /opt/growi/node_modules/elasticsearch/src/lib/transport.js:362:15
      at Timeout.<anonymous> (/opt/growi/node_modules/elasticsearch/src/lib/transport.js:391:7)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
    status: undefined,
    displayName: 'RequestTimeout',
    message: 'Request Timeout after 5000ms',
    body: false
  }
[2020-03-02T00:45:41.741Z]  INFO: express/74 on df0324d7ed2d: ::ffff:192.168.1.15 <-- GET /login HTTP/1.1 200 16348 - Chrome 80.0 Windows 10.0.0 100.68219 ms (req_id=3d358fa5-41cc-4dc8-945f-a252a8cb2ac7)
(node:74) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2020-03-02T00:46:01.897Z] ERROR: growi:routes:login-passport/74 on df0324d7ed2d:
  'ldapauth' passport authentication error:  Error: getaddrinfo ENOTFOUND XXX_authority_ldap
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'XXX_authority_ldap'
  }
Error: getaddrinfo ENOTFOUND XXX_authority_ldap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[2020-03-02T00:46:01.902Z] ERROR: express/74 on df0324d7ed2d: ::ffff:192.168.1.15 <-- POST /login HTTP/1.1 500 148 http://growi.YYYYY.com:3000/login Chrome 80.0 Windows 10.0.0 98.387246 ms (req_id=957fba57-3823-47b8-8e8d-0e5b4370d5ac)
```

最終的には、同じSever内の別コンテナのLDAPサーバ(XXX_authority_ldap)が見つからないとなっているようです。
GrowiのDocker-compose downしコンテナをきれいに削除した後、docker-compose up し、ログイン画面を表示しても、同様のエラーが出てしまうようです。現在はログインできないため、管理メニューからLDAP認証を解除することもできない状況です。

すいませんが、アドバイスよろしくお願いいたします。

**Comment by yuki-takei** [comment]
> Error: getaddrinfo ENOTFOUND XXX_authority_ldap

ということで、そもそも名前解決できていないです。まずは当該ホストからの疎通、次に docker コンテナからの疎通を確認してください。

**Comment by shisyamo** [comment]
別件の回答で、サフィックス付きイメージを利用すると、こちらも解消しました。
Dockerfileでビルドしたものとイメージとで、なぜ、名前解決できたりできなかったりするのか謎ですが、ありがとうございました。

dockerネットワークの問題？うーん、そんなはずはないのですが・・・。

**Comment by m1na1p** [comment]
CentOS8はコンテナが名前解決できないことがあるそうですよ。
こちらのURL記載の”はまりポイント2”の処置で直るかもしれません。
https://www2.filewo.net/wordpress/2020/01/09/centos8%E3%81%ABdocker%E3%82%92%E5%85%A5%E3%82%8C%E3%82%8B%E3%81%A8%E3%80%81%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%81%8C%E5%90%8D%E5%89%8D%E8%A7%A3%E6%B1%BA%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84/

**Comment by yuki-takei** [comment]
こちら個別の環境に依る事象のようですので、issue としては close します。
導入で躓いた際は Slack に書き込んでいただくことでコミュニティによるフォローを行っております。そちらもご利用ください。
