### ISSUE TITLE
日本語設定の初回セットアップ時にsandbox-bootstrap3.mdがない

### ISSUE THREAD

**Issue by m1na1p** [weseek/growi#1885]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS8|
|GROWI     |3.7.2|
|node.js   |12.16.1|
|npm       |6.13.4|
|yarn | 1.22.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome|

How to reproduce? (再現手順)
---------------------------

1. Docker-composeで新規でGrowiを作成
1. 初回起動時のユーザ作成で日本語を選択

What happens? (症状)
---------------------

- 作成後に初回ユーザでログインされずサーバ応答無しとなる

```
[2020-04-10T02:06:09.853Z] ERROR: growi/70 on e9f71bbfd40b:
  Unhandled Rejection: Promise: Promise {
    <rejected> Error: ENOENT: no such file or directory, open '/opt/growi/resource/locales/ja/sandbox-bootstrap3.md'
        at Object.openSync (fs.js:457:3)
        at Object.readFileSync (fs.js:359:35)
        at createPage (/opt/growi/src/server/routes/installer.js:24:25)
        at createInitialPages (/opt/growi/src/server/routes/installer.js:36:19)
        at actions.install (/opt/growi/src/server/routes/installer.js:81:11)
        at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '/opt/growi/resource/locales/ja/sandbox-bootstrap3.md'
    }
  } Reason: Error: ENOENT: no such file or directory, open '/opt/growi/resource/locales/ja/sandbox-bootstrap3.md'
      at Object.openSync (fs.js:457:3)
      at Object.readFileSync (fs.js:359:35)
      at createPage (/opt/growi/src/server/routes/installer.js:24:25)
      at createInitialPages (/opt/growi/src/server/routes/installer.js:36:19)
      at actions.install (/opt/growi/src/server/routes/installer.js:81:11)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path: '/opt/growi/resource/locales/ja/sandbox-bootstrap3.md'
  }

```

What is the expected result? (期待される動作)
-------------------------------------------

- エラーなく初回ユーザを作成できログインできること

Note
--------------------------------------------
事象発生後は一度Growiを再起動させると初回ユーザでログインできます。

**Comment by itizawa** [comment]
issue の報告ありがとうございます。

同様の現象を確認できました。
修正しますので、少々お待ちください。

**Comment by itizawa** [comment]
修正完了しました。

v3.7.3 にバージョンを上げてご確認ください
