### ISSUE TITLE
[HELP] Migration に失敗して起動しません

### ISSUE THREAD

**Issue by mzch** [weseek/growi#2601]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 10.5|
|GROWI     |4.1.0|
|node.js   |v12.18.3|
|npm       |6.14.6|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

How to reproduce? (再現手順)
---------------------------

1. yarn
1. nom run buid:prod
1. npm run server:prod

What happens? (症状)
---------------------

- 以下のエラーが原因で、GROWI が起動しません

```
Aug  3 20:49:03 n08 systemd[1]: Started GROWI - Enhanced Crowi..
Aug  3 20:49:04 n08 npm[15687]: > growi@4.1.0 preserver:prod /srv/growi/growi
Aug  3 20:49:04 n08 npm[15687]: > npm run migrate
Aug  3 20:49:04 n08 npm[15687]: > growi@4.1.0 migrate /srv/growi/growi
Aug  3 20:49:04 n08 npm[15687]: > npm run migrate:up
Aug  3 20:49:05 n08 npm[15687]: > growi@4.1.0 migrate:up /srv/growi/growi
Aug  3 20:49:05 n08 npm[15687]: > migrate-mongo up -f config/migrate.js
Aug  3 20:49:06 n08 npm[15687]: the options [useFindAndModify] is not supported
Aug  3 20:49:36 n08 npm[15687]: ERROR: Server selection timed out after 30000 ms
Aug  3 20:49:36 n08 npm[15687]: npm ERR! code ELIFECYCLE
Aug  3 20:49:36 n08 npm[15687]: npm ERR! errno 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR! growi@4.1.0 migrate:up: `migrate-mongo up -f config/migrate.js`
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Exit status 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR!
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Failed at the growi@4.1.0 migrate:up script.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! A complete log of this run can be found in:
Aug  3 20:49:36 n08 npm[15687]: npm ERR!     /srv/growi/.npm/_logs/2020-08-03T11_49_36_151Z-debug.log
Aug  3 20:49:36 n08 npm[15687]: npm ERR! code ELIFECYCLE
Aug  3 20:49:36 n08 npm[15687]: npm ERR! errno 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR! growi@4.1.0 migrate: `npm run migrate:up`
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Exit status 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR!
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Failed at the growi@4.1.0 migrate script.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! A complete log of this run can be found in:
Aug  3 20:49:36 n08 npm[15687]: npm ERR!     /srv/growi/.npm/_logs/2020-08-03T11_49_36_219Z-debug.log
Aug  3 20:49:36 n08 npm[15687]: npm ERR! code ELIFECYCLE
Aug  3 20:49:36 n08 npm[15687]: npm ERR! errno 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR! growi@4.1.0 preserver:prod: `npm run migrate`
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Exit status 1
Aug  3 20:49:36 n08 npm[15687]: npm ERR!
Aug  3 20:49:36 n08 npm[15687]: npm ERR! Failed at the growi@4.1.0 preserver:prod script.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug  3 20:49:36 n08 npm[15687]: npm ERR! A complete log of this run can be found in:
Aug  3 20:49:36 n08 npm[15687]: npm ERR!     /srv/growi/.npm/_logs/2020-08-03T11_49_36_281Z-debug.log
Aug  3 20:49:36 n08 systemd[1]: growi.service: Main process exited, code=exited, status=1/FAILURE
Aug  3 20:49:36 n08 systemd[1]: growi.service: Failed with result 'exit-code'.
Aug  3 20:49:36 n08 systemd[1]: growi.service: Service RestartSec=100ms expired, scheduling restart.
Aug  3 20:49:36 n08 systemd[1]: growi.service: Scheduled restart job, restart counter is at 26.
Aug  3 20:49:36 n08 systemd[1]: Stopped GROWI - Enhanced Crowi..
```

- debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/srv/growi/.ndenv/versions/v12.18.3/bin/node',
1 verbose cli   '/srv/growi/.ndenv/versions/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'migrate:up'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'premigrate:up', 'migrate:up', 'postmigrate:up' ]
5 info lifecycle growi@4.1.0~premigrate:up: growi@4.1.0
6 info lifecycle growi@4.1.0~migrate:up: growi@4.1.0
7 verbose lifecycle growi@4.1.0~migrate:up: unsafe-perm in lifecycle true
8 verbose lifecycle growi@4.1.0~migrate:up: PATH: /srv/growi/.ndenv/versions/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/growi/growi/node_modules/.bin:/srv/growi/.ndenv/versions/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/growi/growi/node_modules/.bin:/srv/growi/.ndenv/versions/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/growi/growi/node_modules/.bin:/srv/growi/.ndenv/versions/v12.18.3/bin:/srv/growi/.ndenv/libexec:/srv/growi/.ndenv/plugins/node-build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle growi@4.1.0~migrate:up: CWD: /srv/growi/growi
10 silly lifecycle growi@4.1.0~migrate:up: Args: [ '-c', 'migrate-mongo up -f config/migrate.js' ]
11 silly lifecycle growi@4.1.0~migrate:up: Returned: code: 1  signal: null
12 info lifecycle growi@4.1.0~migrate:up: Failed to exec migrate:up script
13 verbose stack Error: growi@4.1.0 migrate:up: `migrate-mongo up -f config/migrate.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/srv/growi/.ndenv/versions/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/srv/growi/.ndenv/versions/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid growi@4.1.0
15 verbose cwd /srv/growi/growi
16 verbose Linux 4.19.0-10-amd64
17 verbose argv "/srv/growi/.ndenv/versions/v12.18.3/bin/node" "/srv/growi/.ndenv/versions/v12.18.3/bin/npm" "run" "migrate:up"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error growi@4.1.0 migrate:up: `migrate-mongo up -f config/migrate.js`
22 error Exit status 1
23 error Failed at the growi@4.1.0 migrate:up script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

What is the expected result? (期待される動作)
-------------------------------------------

- 正常に起動すること。

**Comment by shield-9** [comment]
エラーメッセージでそのままググった限り、mongooseのバージョンが古いと出るエラーのようです。yarnコマンドを打った時に何かエラーが出ていたりしませんか？

また、推奨手順は`yarn migrate`のようなので、そちらを試してみてもいいかもしれないですね。

**Comment by mzch** [comment]
すみません。MongoDB 側のエラーでした。よく調べずに申し訳ない。
