### ISSUE TITLE
Full Text Search doesn't work (全文検索ができない) and Rebuilding Index has failed

### ISSUE THREAD

**Issue by yamamotoalex** [weseek/growi#2656]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS 7.8|
|GROWI     |4.1.2|
|node.js   |14.8.0|
|npm       |6.14.7|
|elasticsearch       |7.8.1-1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google chrome  84.0.4147.125|

How to reproduce? (再現手順)
---------------------------
ほぼこのWebページと同じ手順（各モジュールのバージョンは異なるが）
でインストールを実施
https://docs.growi.org/ja/admin-guide/getting-started/centos.html

2回行ったが症状変わらず

What happens? (症状)
---------------------------

全文検索に文字列を入れてもhitしない
Full Text Search doesn't work and no hits

インデックスのリビルドをすると失敗する
Rebuilding Index has failed.

![image](https://user-images.githubusercontent.com/69581222/90310574-a69c3980-df2d-11ea-82cd-844eedb53366.png)

What is the expected result? (期待される動作)
-------------------------------------------

-　全文検索ができること 
- 

Note
----

- 
- 
![image](https://user-images.githubusercontent.com/69581222/90310695-e6afec00-df2e-11ea-9072-27eb0e2946d0.png)

**Comment by shield-9** [comment]
ESのバージョンがサポートされていない系統ですね。6系で試してみてください。
https://github.com/weseek/growi#dependencies

**Comment by yamamotoalex** [comment]
Elasticsearchを6.8.12で試してみました。
```
[root@main-sv growi]# rpm -qa | grep elastic
elasticsearch-6.8.12-1.noarch
```

当初のエラーは出なくなりましたが、IndexのRebuildに失敗します
検索もできないです

![image](https://user-images.githubusercontent.com/69581222/90841814-a15d4580-e398-11ea-83be-96f6a496a6b3.png)

プラグインは正しく入っていると思います
```
[root@main-sv growi]# /usr/share/elasticsearch/bin/elasticsearch-plugin list
analysis-icu
analysis-kuromoji
```
```
[root@main-sv growi]# /usr/share/elasticsearch/bin/elasticsearch -v
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2020-08-21T10:24:01,916][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.12.jar:6.8.12]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:103) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
        ... 6 more
```

**Comment by yamamotoalex** [comment]
申し訳ありません。elasticsearchを再起動したところ、エラーがなくなりました。
解決しました。
ありがとうございます。
