### ISSUE TITLE
growi4.1.4のビルドに失敗する

### ISSUE THREAD

**Issue by AnaTofuZ** [weseek/growi#2759]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20 |
|GROWI     |4.1.4|
|node.js   |x.y.z|
|npm       |x.y.z|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1. growi4.1.3が動いていたホストで下記コマンドを実行

```
docker-compose stop
docker-compose rm -f app
docker rmi weseek/growi:4
docker-compose build
docker-compose up -d
```

2. HTTPでアクセスに行くと画面が表示されない

What happens? (症状)
---------------------

- ログを確認したところappのビルドに失敗している

```
app_1            | > npm run migrate:up
app_1            |
app_1            |
app_1            | > growi@4.1.4 migrate:up /opt/growi
app_1            | > migrate-mongo up -f config/migrate.js
app_1            |
app_1            | (node:54) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
app_1            | (Use `node --trace-warnings ...` to show where the warning was created)
app_1            | (node:54) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
app_1            | (node:54) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
app_1            | (node:54) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
app_1            | the options [useFindAndModify] is not supported
app_1            |
app_1            | > growi@4.1.4 server:prod /opt/growi
app_1            | > env-cmd -f config/env.prod.js node src/server/app.js
app_1            |
app_1            | (node:72) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
app_1            | (Use `node --trace-deprecation ...` to show where the warning was created)
app_1            | [2020-09-09T04:38:44.367Z] ERROR: growi/72 on de5de342fd7f: An error occurred, unable to start the server
app_1            | [2020-09-09T04:38:44.368Z] ERROR: growi/72 on de5de342fd7f: Unexpected token s in JSON at position 0
app_1            |   SyntaxError: Unexpected token s in JSON at position 0
app_1            |       at JSON.parse (<anonymous>)
app_1            |       at ConfigLoader.loadFromDB (/opt/growi/src/server/service/config-loader.js:378:38)
app_1            |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
app_1            |       at async ConfigLoader.load (/opt/growi/src/server/service/config-loader.js:341:26)
app_1            |       at async ConfigManager.loadConfigs (/opt/growi/src/server/service/config-manager.js:45:25)
app_1            |       at async Crowi.init (/opt/growi/src/server/crowi/index.js:83:3)
app_1            |       at async Crowi.start (/opt/growi/src/server/crowi/index.js:397:3)
app_1            | npm ERR! code ELIFECYCLE
app_1            | npm ERR! errno 1
```

What is the expected result? (期待される動作)
-------------------------------------------

- SyntaxErrorの解消

- 

Note
------------

- 4.1.3で再ビルドしても同様のエラーが発生しました

**Comment by yuki-takei** [comment]
@AnaTofuZ ご報告ありがとうございます。再現確認しました。
v4.1.5 をリリースしますので今しばらくお待ちください。

**Comment by AnaTofuZ** [comment]
4.1.5のリリースを確認し、再度ビルドしたところ、立ち上がるのを確認しました。
対応ありがとうございます!
