### ISSUE TITLE
ページに利用されていない添付ファイル（画像ファイル）が含まれていると、そのページの画像が表示されなくなる

### ISSUE THREAD

**Issue by kunitake** [weseek/growi#2819]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 20.04 LTS|
|GROWI     |4.1.1 〜 4.1.6|
|node.js   |14.11.0|
|npm       |6.14.8|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.6|
|browser   |Google Chrome 85.0.4183.102（Official Build）|

How to reproduce? (再現手順)
---------------------------

1. 4.1.0 で、添付画像を複数枚添付し、一部使わない状態とする。

[
![attachments](https://user-images.githubusercontent.com/1456158/94228293-9e291c80-ff37-11ea-87a9-f4b5f31c534f.png)
](url)

2. Growi を 4.1.1 を含むそれ以降に version up する

3. 該当ページを閲覧すると下記のようなエラーが出て、画像が表示されなくなる

```
app_1            | [2020-09-25T02:28:23.664Z] ERROR: growi/71 on 6b26852b2df9:
app_1            |   Unhandled Rejection: Promise: Promise {
app_1            |     <rejected> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
app_1            |         at validateString (internal/validators.js:122:11)
app_1            |         at Url.parse (url.js:159:3)
app_1            |         at Object.urlParse [as parse] (url.js:154:13)
app_1            |         at /opt/growi/src/server/middlewares/certify-shared-file.js:10:26
app_1            |         at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |         at next (/opt/growi/node_modules/express/lib/router/route.js:137:13)
app_1            |         at Route.dispatch (/opt/growi/node_modules/express/lib/router/route.js:112:3)
app_1            |         at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |         at /opt/growi/node_modules/express/lib/router/index.js:281:22
app_1            |         at param (/opt/growi/node_modules/express/lib/router/index.js:354:14)
app_1            |         at param (/opt/growi/node_modules/express/lib/router/index.js:365:14)
app_1            |         at Function.process_params (/opt/growi/node_modules/express/lib/router/index.js:410:3)
app_1            |         at next (/opt/growi/node_modules/express/lib/router/index.js:275:10)
app_1            |         at /opt/growi/node_modules/express-bunyan-logger/index.js:197:9
app_1            |         at /opt/growi/node_modules/express-bunyan-logger/index.js:12:9
app_1            |         at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |         at trim_prefix (/opt/growi/node_modules/express/lib/router/index.js:317:13)
app_1            |         at /opt/growi/node_modules/express/lib/router/index.js:284:7
app_1            |         at Function.process_params (/opt/growi/node_modules/express/lib/router/index.js:335:12)
app_1            |         at next (/opt/growi/node_modules/express/lib/router/index.js:275:10)
app_1            |         at /opt/growi/node_modules/i18next-express-middleware/lib/index.js:94:7
app_1            |         at I18n.loadLanguages (/opt/growi/node_modules/i18next/dist/cjs/i18next.js:2206:23) {
app_1            |       code: 'ERR_INVALID_ARG_TYPE'
app_1            |     }
app_1            |   } Reason: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
app_1            |       at validateString (internal/validators.js:122:11)
app_1            |       at Url.parse (url.js:159:3)
app_1            |       at Object.urlParse [as parse] (url.js:154:13)
app_1            |       at /opt/growi/src/server/middlewares/certify-shared-file.js:10:26
app_1            |       at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |       at next (/opt/growi/node_modules/express/lib/router/route.js:137:13)
app_1            |       at Route.dispatch (/opt/growi/node_modules/express/lib/router/route.js:112:3)
app_1            |       at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |       at /opt/growi/node_modules/express/lib/router/index.js:281:22
app_1            |       at param (/opt/growi/node_modules/express/lib/router/index.js:354:14)
app_1            |       at param (/opt/growi/node_modules/express/lib/router/index.js:365:14)
app_1            |       at Function.process_params (/opt/growi/node_modules/express/lib/router/index.js:410:3)
app_1            |       at next (/opt/growi/node_modules/express/lib/router/index.js:275:10)
app_1            |       at /opt/growi/node_modules/express-bunyan-logger/index.js:197:9
app_1            |       at /opt/growi/node_modules/express-bunyan-logger/index.js:12:9
app_1            |       at Layer.handle [as handle_request] (/opt/growi/node_modules/express/lib/router/layer.js:95:5)
app_1            |       at trim_prefix (/opt/growi/node_modules/express/lib/router/index.js:317:13)
app_1            |       at /opt/growi/node_modules/express/lib/router/index.js:284:7
app_1            |       at Function.process_params (/opt/growi/node_modules/express/lib/router/index.js:335:12)
app_1            |       at next (/opt/growi/node_modules/express/lib/router/index.js:275:10)
app_1            |       at /opt/growi/node_modules/i18next-express-middleware/lib/index.js:94:7
app_1            |       at I18n.loadLanguages (/opt/growi/node_modules/i18next/dist/cjs/i18next.js:2206:23) {
app_1            |     code: 'ERR_INVALID_ARG_TYPE'
app_1            |   }
```

What happens? (症状)
---------------------
In Use ではない添付ファイルが含まれるページの添付ファイルが展開されなくなる。

What is the expected result? (期待される動作)
-------------------------------------------
添付ファイル（画像ファイル）が表示される。

Note
----
一時的な回避策としては、4.1.0 にバージョンを戻して、In Use ではない添付ファイルを削除してから4.1.1 以降に version upすると、添付ファイルが表示されます。

**Comment by yuki-takei** [comment]
@kunitake ご報告ありがとうございます。
手元で試した感じ、こちらではあいにく再現しないのですが、貼っていただいたエラーから undefined な値の取り扱いが原因というのはわかりましたので修正に入ります。

**Comment by kunitake** [comment]
すみません、カスタマイズで、リンクには noreferrer 付けて、リファラを無効化するようにしていたので、それが影響したかもしれません。

- カスタムHTMLヘッダ

```
<meta name=referrer content="no-referrer">
```

- カスタムスクリプト

```
window.onload = function () {
  var ids = ['wrapper'];
  for (var i = 0; i < ids.length; i++) {
       var as = document.getElementById(ids[i]).getElementsByTagName('a');
        for (var j = 0; j < as.length; j++) {
          as[j].setAttribute('ref', 'noreferrer');
        }
  }
};
```

とか

**Comment by yuki-takei** [comment]
ちょうどこちらでも同一サイトで referer 無効化するユーザーにどれくらい配慮すべきか、というトピックで議論していました。

結果として「referer を送ってこないクライアントは、共有リンク機能を利用した添付ファイルは閲覧できない」という仕様でいいんじゃないかというところで落ち着きつつあります。(ただし現在は Unhandled Rejection になってしまっているのでそれは修正する)

**Comment by kunitake** [comment]
カスタムHTMLヘッダを

```
<meta name=referrer content="origin-when-crossorigin">
```

に変更することでも回避可能なことを確認しました。

**Comment by yuki-takei** [comment]
改修完了しました。v4.2.0 または v4.1.7 リリースをお待ちください。
