### ISSUE TITLE
Bug: A version mismatch error occured when detecting archive data

### ISSUE THREAD

**Issue by yuki-takei** [weseek/growi#2856]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |v4.1.8-RC|

How to reproduce? (再現手順)
---------------------------

1. Install
1. Export archive
1. Flush MongoDB and install cleanly again without removing archive file in `/tmp/imports`
1. Access to `/admin/importer`

What happens? (症状)
---------------------

```
14:09:33.781Z ERROR growi:services:ImportService:
  the versions are not met Error: the version of this growi and the growi that exported the data are not met
      at ImportService.validate (/workspace/growi/src/server/service/import.js:487:13)
      at ImportService.getStatus (/workspace/growi/src/server/service/import.js:155:14)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /workspace/growi/src/server/routes/apiv3/import.js:159:22
```

What is the expected result? (期待される動作)
-------------------------------------------

- The error is not occured

**Comment by yuki-takei** [comment]
This is not a problem because I misunderstood that.
