### ISSUE TITLE
Normalize Indeces でエラー

### ISSUE THREAD

**Issue by mzch** [weseek/growi#2916]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Debian 10.6|
|GROWI     |4.1.9|
|node.js   |v12.19.0|
|npm       |6.14.8|
|Using Docker|no|
|Using [growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.15.7|
|browser   |Chrome 86.0.4240.80|

How to reproduce? (再現手順)
---------------------------

1. Admin エリアの Full Text Search Management タグを選択
1. Indices Status が `REBUILDING or BROKEN`
1. `Normalize Indeces` ボタンをクリック

What happens? (症状)
---------------------

1. `Success Normalize has succeeded` と同時にエラーが表示される

<img width="1490" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/96412153-9ef65b00-1224-11eb-9d7e-47c6a70d24d7.png">

- log
```
Oct 19 00:07:56 v22 yarn[31447]: #033[90m[2020-10-19T07:07:56.407Z]#033[39m #033[31mERROR#033[39m: growi/31514 on v22:
Oct 19 00:07:56 v22 yarn[31447]: #033[90m  #033[36mUnhandled Rejection: Promise: Promise {
Oct 19 00:07:56 v22 yarn[31447]:     <rejected> StatusCodeError: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text,
fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime,
 type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]
Oct 19 00:07:56 v22 yarn[31447]:         at respond (/srv/growi/growi/node_modules/elasticsearch/src/lib/transport.js:315:15)
Oct 19 00:07:56 v22 yarn[31447]:         at checkRespForFailure (/srv/growi/growi/node_modules/elasticsearch/src/lib/transport.js:274:7)
Oct 19 00:07:56 v22 yarn[31447]:         at HttpConnector.<anonymous> (/srv/growi/growi/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
Oct 19 00:07:56 v22 yarn[31447]:         at IncomingMessage.wrapper (/srv/growi/growi/node_modules/lodash/lodash.js:4929:19)
Oct 19 00:07:56 v22 yarn[31447]:         at IncomingMessage.emit (events.js:326:22)
Oct 19 00:07:56 v22 yarn[31447]:         at IncomingMessage.EventEmitter.emit (domain.js:483:12)
Oct 19 00:07:56 v22 yarn[31447]:         at endReadableNT (_stream_readable.js:1223:12)
Oct 19 00:07:56 v22 yarn[31447]:         at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Oct 19 00:07:56 v22 yarn[31447]:       status: 400,
Oct 19 00:07:56 v22 yarn[31447]:       displayName: 'BadRequest',
Oct 19 00:07:56 v22 yarn[31447]:       path: '/growi',
Oct 19 00:07:56 v22 yarn[31447]:       query: {},
Oct 19 00:07:56 v22 yarn[31447]:       body: { error: [Object], status: 400 },
Oct 19 00:07:56 v22 yarn[31447]:       statusCode: 400,
Oct 19 00:07:56 v22 yarn[31447]:       response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Roo
t mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_a
t={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=
text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]"}],"type":"mapper_parsing_exception","
reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=
standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [page
s : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}},
 like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={for
mat=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text
}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}
, username={type=keyword}}}]"}},"status":400}',
Oct 19 00:07:56 v22 yarn[31447]:       toString: [Function],
Oct 19 00:07:56 v22 yarn[31447]:       toJSON: [Function]
Oct 19 00:07:56 v22 yarn[31447]:     }
Oct 19 00:07:56 v22 yarn[31447]:   } Reason: StatusCodeError: [mapper_parsing_exception] Root mapping definition has unsupported parameters:  [pages : {properties={comment_count={type=integer}, granted_users={type=keyword}, path={type=text, fields={ja={analyzer=japanese, type=text}, raw={analyzer=keyword, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, like_count={type=integer}, granted_group={type=keyword}, updated_at={format=dateOptionalTime, type=date}, created_at={format=dateOptionalTime, type=date}, bookmark_count={type=integer}, body={type=text, fields={ja={analyzer=japanese, type=text}, en={search_analyzer=standard, analyzer=english_edge_ngram, type=text}}}, grant={type=integer}, tag_names={type=keyword}, username={type=keyword}}}]
```

What is the expected result? (期待される動作)
-------------------------------------------
`Indices Status` が正常

**Comment by mzch** [comment]
すみません。ElasticSearch が 7.x になってました。6.x にダウングレードしたら解決しました。
