### ISSUE TITLE
ページを再帰的に移動すると親ページのみが移動されない

### ISSUE THREAD

**Issue by rary21** [weseek/growi#3557]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |20.04.2 LTS (Focal Fossa) WSL2|
|GROWI     |4.2.12|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 89.0.4389.90|

How to reproduce? (再現手順)
---------------------------

1. `/b/bb` のように階層構造を持つページを作成する
1. `/b` 上でページの移動を行う。オプションは `再帰的に移動/名前変更` のみ有効にし、 `/b/` を `/share/b` などに移動する

What happens? (症状)
---------------------

- `/share/b/bb` はアクセス可能だが、 `/share/b` へアクセスをしてもページが存在しないと表示される
- lsxプラグインによる表示には、 `share/b/bb` が表示され、 `/b/bb` は消えている
- `docker-compose logs` によって下記エラーメッセージが表示される。
```
app_1            | [2021-03-25T02:54:32.160Z] ERROR: growi/75 on df020c58005b:
app_1            |   Unhandled Rejection: Promise: Promise {
app_1            |     <rejected> CastError: Cast to ObjectId failed for value "b" at path "_id" for model "ShareLink"
app_1            |         at model.Query.exec (/opt/growi/node_modules/mongoose/lib/query.js:4381:21)
app_1            |         at model.Query.Query.then (/opt/growi/node_modules/mongoose/lib/query.js:4473:15)
app_1            |         at runMicrotasks (<anonymous>)
app_1            |         at processTicksAndRejections (internal/process/task_queues.js:93:5)
app_1            |         at runNextTicks (internal/process/task_queues.js:62:3)
app_1            |         at processImmediate (internal/timers.js:434:9) {
app_1            |       messageFormat: undefined,
app_1            |       stringValue: '"b"',
app_1            |       kind: 'ObjectId',
app_1            |       value: 'b',
app_1            |       path: '_id',
app_1            |       reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
app_1            |           at new ObjectID (/opt/growi/node_modules/bson/lib/bson/objectid.js:59:11)
app_1            |           at castObjectId (/opt/growi/node_modules/mongoose/lib/cast/objectid.js:25:12)
app_1            |           at ObjectId.cast (/opt/growi/node_modules/mongoose/lib/schema/objectid.js:267:12)
app_1            |           at ObjectId.SchemaType.applySetters (/opt/growi/node_modules/mongoose/lib/schematype.js:1075:12)
app_1            |           at ObjectId.SchemaType._castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1510:15)
app_1            |           at ObjectId.SchemaType.castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1500:15)
app_1            |           at ObjectId.SchemaType.castForQueryWrapper (/opt/growi/node_modules/mongoose/lib/schematype.js:1477:20)
app_1            |           at cast (/opt/growi/node_modules/mongoose/lib/cast.js:331:32)
app_1            |           at model.Query.Query.cast (/opt/growi/node_modules/mongoose/lib/query.js:4782:12)
app_1            |           at model.Query.Query._castConditions (/opt/growi/node_modules/mongoose/lib/query.js:1874:10)
app_1            |           at model.Query.<anonymous> (/opt/growi/node_modules/mongoose/lib/query.js:2131:8)
app_1            |           at model.Query._wrappedThunk [as _findOne] (/opt/growi/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
app_1            |           at /opt/growi/node_modules/kareem/index.js:369:33
app_1            |           at processTicksAndRejections (internal/process/task_queues.js:75:11)
app_1            |           at runNextTicks (internal/process/task_queues.js:62:3)
app_1            |           at processImmediate (internal/timers.js:434:9)
app_1            |     }
app_1            |   } Reason: CastError: Cast to ObjectId failed for value "b" at path "_id" for model "ShareLink"
app_1            |       at model.Query.exec (/opt/growi/node_modules/mongoose/lib/query.js:4381:21)
app_1            |       at model.Query.Query.then (/opt/growi/node_modules/mongoose/lib/query.js:4473:15)
app_1            |       at runMicrotasks (<anonymous>)
app_1            |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
app_1            |       at runNextTicks (internal/process/task_queues.js:62:3)
app_1            |       at processImmediate (internal/timers.js:434:9) {
app_1            |     messageFormat: undefined,
app_1            |     stringValue: '"b"',
app_1            |     kind: 'ObjectId',
app_1            |     value: 'b',
app_1            |     path: '_id',
app_1            |     reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
app_1            |         at new ObjectID (/opt/growi/node_modules/bson/lib/bson/objectid.js:59:11)
app_1            |         at castObjectId (/opt/growi/node_modules/mongoose/lib/cast/objectid.js:25:12)
app_1            |         at ObjectId.cast (/opt/growi/node_modules/mongoose/lib/schema/objectid.js:267:12)
app_1            |         at ObjectId.SchemaType.applySetters (/opt/growi/node_modules/mongoose/lib/schematype.js:1075:12)
app_1            |         at ObjectId.SchemaType._castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1510:15)
app_1            |         at ObjectId.SchemaType.castForQuery (/opt/growi/node_modules/mongoose/lib/schematype.js:1500:15)
app_1            |         at ObjectId.SchemaType.castForQueryWrapper (/opt/growi/node_modules/mongoose/lib/schematype.js:1477:20)
app_1            |         at cast (/opt/growi/node_modules/mongoose/lib/cast.js:331:32)
app_1            |         at model.Query.Query.cast (/opt/growi/node_modules/mongoose/lib/query.js:4782:12)
app_1            |         at model.Query.Query._castConditions (/opt/growi/node_modules/mongoose/lib/query.js:1874:10)
app_1            |         at model.Query.<anonymous> (/opt/growi/node_modules/mongoose/lib/query.js:2131:8)
app_1            |         at model.Query._wrappedThunk [as _findOne] (/opt/growi/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
app_1            |         at /opt/growi/node_modules/kareem/index.js:369:33
app_1            |         at processTicksAndRejections (internal/process/task_queues.js:75:11)
app_1            |         at runNextTicks (internal/process/task_queues.js:62:3)
app_1            |         at processImmediate (internal/timers.js:434:9)
app_1            |   }
```

What is the expected result? (期待される動作)
-------------------------------------------

- `/share/b` にアクセスができる

Note
----

- CentOS 7で構築した場合も同じ結果が得られました。

**Comment by itizawa** [comment]
@rary21 
GROWI をご利用いただきありがとうございます。

ご不便をおかけし申し訳ございません。
こちらのエラーですが本来 作成できないはずの `/share` の配下に、ページが作成されてしまったのが原因でした。

そもそも **`/share` にはページを移動・複製ができない** ことがあるべき挙動です。
そのため https://github.com/weseek/growi/pull/3559 の修正で `/share` 配下には移動・複製できないような修正を行いました。
Issue を報告いただきありがとうございました。

今回誤って作成された `share/b/bb` のページですが、以下の手順で復元できます。
- `/share` にアクセスする。
  - <img width="1611" alt="スクリーンショット 2021-03-25 15 11 07" src="https://user-images.githubusercontent.com/48426654/112427066-56673e80-8d7c-11eb-839a-ae68b27031a1.png">
- **ページを作成する** を押しページを作成する。
- 作成した `/share` のページに対し、`/temporary ` のような一時的なバスへ移動を行う。この時 `再帰的に移動/名前変更` を有効にする。

以上の操作を現在のバージョンでお試しください。

お手数おかけしますが、ご確認お願いいたします。
何かご不明な点がございましたらご気軽にご連絡ください。

**Comment by rary21** [comment]
@itizawa 
ご回答ありがとうございます。
レアケースをたまたま踏んでしまっていたのですね。
`share` フォルダ以外への移動が正常に動作することは確認できました。
教えていただいた手順に従い、見れなくなったページも全て復旧することが確認できましたのでクローズいたします。
