### ISSUE TITLE
Bug: GROWI does not work properly when MONGODB_URI contains '?readPreference=secondary'

### ISSUE THREAD

**Issue by skomma** [weseek/growi#3848]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Linux |
|GROWI     | 4.2.14 |
|Using Docker|yes|

How to reproduce? (再現手順)
---------------------------

### Case.1

Before starting a fresh GROWI, set `?readPreference=secondary` in MONGODB_URI.

1. Create MongoDB Replica set
1. Start GROWI with adding '?replicaSet=XXX&readPreference=secondary' in MONGODB_URI

### Case.2

After creating a fresh GROWI with no `readPrefernce` parameter, set `?readPreference=secondary` in MONGODB_URI.

1. Create MongoDB Replica set
2. Start GROWI with no `readPreference` parameter.
3. Restart GROWI with adding `?readPreference=secondary` in MONGODB_URI

What happens? (症状)
---------------------

### Case1.

- GROWI cannot start
- The below error occurs:

```
app_1_bde8b9c3b67a | > growi@4.2.18 migrate:up /opt/growi
app_1_bde8b9c3b67a | > migrate-mongo up -f config/migrate.js
app_1_bde8b9c3b67a |
app_1_bde8b9c3b67a | the options [useFindAndModify] is not supported
app_1_bde8b9c3b67a | 20:34:53.605Z  INFO growi:migrate:make-email-unique: Start migration
app_1_bde8b9c3b67a | (node:56) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
app_1_bde8b9c3b67a | (Use `node --trace-deprecation ...` to show where the warning was created)
app_1_bde8b9c3b67a | 20:34:53.636Z  INFO growi:migrate:make-email-unique: Invoking syncIndexes
app_1_bde8b9c3b67a | (node:56) UnhandledPromiseRejectionWarning: MongoError: not master
app_1_bde8b9c3b67a |     at MessageStream.messageHandler (/opt/growi/node_modules/mongodb/lib/cmap/connection.js:268:20)
app_1_bde8b9c3b67a |     at MessageStream.emit (events.js:376:20)
app_1_bde8b9c3b67a |     at processIncomingData (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
app_1_bde8b9c3b67a |     at MessageStream._write (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
app_1_bde8b9c3b67a |     at writeOrBuffer (internal/streams/writable.js:358:12)
app_1_bde8b9c3b67a |     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
app_1_bde8b9c3b67a |     at Socket.ondata (internal/streams/readable.js:745:22)
app_1_bde8b9c3b67a |     at Socket.emit (events.js:376:20)
app_1_bde8b9c3b67a |     at addChunk (internal/streams/readable.js:309:12)
app_1_bde8b9c3b67a |     at readableAddChunk (internal/streams/readable.js:284:9)
app_1_bde8b9c3b67a |     at Socket.Readable.push (internal/streams/readable.js:223:10)
app_1_bde8b9c3b67a |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Case.2

- When accessing to `/_api/v3/healthcheck`, the request will be timed out.
- When starting GROWI, the below error occurred:

```
app_1_bde8b9c3b67a | > growi@4.2.18 server:prod /opt/growi
app_1_bde8b9c3b67a | > env-cmd -f config/env.prod.js node --expose_gc src/server/app.js
app_1_bde8b9c3b67a |
app_1_bde8b9c3b67a | (node:74) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
app_1_bde8b9c3b67a | (Use `node --trace-deprecation ...` to show where the warning was created)
app_1_bde8b9c3b67a | [2021-06-03T20:36:23.478Z] ERROR: growi/74 on 80c9a7d82a04:
app_1_bde8b9c3b67a |   Unhandled Rejection: Promise: Promise {
app_1_bde8b9c3b67a |     <rejected> MongoError: not master
app_1_bde8b9c3b67a |         at MessageStream.messageHandler (/opt/growi/node_modules/mongodb/lib/cmap/connection.js:268:20)
app_1_bde8b9c3b67a |         at MessageStream.emit (events.js:376:20)
app_1_bde8b9c3b67a |         at processIncomingData (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
app_1_bde8b9c3b67a |         at MessageStream._write (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
app_1_bde8b9c3b67a |         at writeOrBuffer (internal/streams/writable.js:358:12)
app_1_bde8b9c3b67a |         at MessageStream.Writable.write (internal/streams/writable.js:303:10)
app_1_bde8b9c3b67a |         at Socket.ondata (internal/streams/readable.js:745:22)
app_1_bde8b9c3b67a |         at Socket.emit (events.js:376:20)
app_1_bde8b9c3b67a |         at addChunk (internal/streams/readable.js:309:12)
app_1_bde8b9c3b67a |         at readableAddChunk (internal/streams/readable.js:284:9)
app_1_bde8b9c3b67a |         at Socket.Readable.push (internal/streams/readable.js:223:10)
app_1_bde8b9c3b67a |         at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
app_1_bde8b9c3b67a |       topologyVersion: { processId: 60b93c4bff13ab0ec36d4099, counter: 4 },
app_1_bde8b9c3b67a |       operationTime: Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1622752570 },
app_1_bde8b9c3b67a |       ok: 0,
app_1_bde8b9c3b67a |       code: 10107,
app_1_bde8b9c3b67a |       codeName: 'NotWritablePrimary',
app_1_bde8b9c3b67a |       '$clusterTime': { clusterTime: [Timestamp], signature: [Object] }
app_1_bde8b9c3b67a |     }
app_1_bde8b9c3b67a |   } Reason: MongoError: not master
app_1_bde8b9c3b67a |       at MessageStream.messageHandler (/opt/growi/node_modules/mongodb/lib/cmap/connection.js:268:20)
app_1_bde8b9c3b67a |       at MessageStream.emit (events.js:376:20)
app_1_bde8b9c3b67a |       at processIncomingData (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
app_1_bde8b9c3b67a |       at MessageStream._write (/opt/growi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
app_1_bde8b9c3b67a |       at writeOrBuffer (internal/streams/writable.js:358:12)
app_1_bde8b9c3b67a |       at MessageStream.Writable.write (internal/streams/writable.js:303:10)
app_1_bde8b9c3b67a |       at Socket.ondata (internal/streams/readable.js:745:22)
app_1_bde8b9c3b67a |       at Socket.emit (events.js:376:20)
app_1_bde8b9c3b67a |       at addChunk (internal/streams/readable.js:309:12)
app_1_bde8b9c3b67a |       at readableAddChunk (internal/streams/readable.js:284:9)
app_1_bde8b9c3b67a |       at Socket.Readable.push (internal/streams/readable.js:223:10)
app_1_bde8b9c3b67a |       at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
app_1_bde8b9c3b67a |     topologyVersion: { processId: 60b93c4bff13ab0ec36d4099, counter: 4 },
app_1_bde8b9c3b67a |     operationTime: Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1622752570 },
app_1_bde8b9c3b67a |     ok: 0,
app_1_bde8b9c3b67a |     code: 10107,
app_1_bde8b9c3b67a |     codeName: 'NotWritablePrimary',
app_1_bde8b9c3b67a |     '$clusterTime': {
app_1_bde8b9c3b67a |       clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 4, high_: 1622752570 },
app_1_bde8b9c3b67a |       signature: { hash: [Binary], keyId: 0 }
app_1_bde8b9c3b67a |     }
app_1_bde8b9c3b67a |   }
```

What is the expected result? (期待される動作)
-------------------------------------------

GROWI works correctly even when `readPreference` is set in MONGODB_URI.

Note
----

I made docker-compose.yml to reproduce easily.

```bash
git clone https://github.com/skomma/growi-docker-compose
cd growi-docker-compose
docker-compose up mongo1 mongo2 mongo3
docker-compose exec mongo1 mongo /init.js
docker-compose up app
```

**Comment by yuki-takei** [comment]
## Memo

- https://mongoosejs.com/docs/connections.html#options
- https://mongodb.github.io/node-mongodb-native/api-generated/replset.html

**Comment by yuki-takei** [comment]
in my devcontainer...

```
node ➜ /workspace/growi (master ✗) $ yarn migrate
yarn run v1.22.5
$ npm run migrate:up
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1623238359040-0.3492483402445945/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> growi@4.2.21-RC migrate:up /workspace/growi
> migrate-mongo up -f config/migrate.js

the options [useFindAndModify] is not supported
11:32:39.707Z  INFO growi:migrate:make-email-unique: Start migration
(node:4945) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
11:32:39.766Z  INFO growi:migrate:make-email-unique: Invoking syncIndexes
(node:4945) UnhandledPromiseRejectionWarning: MongoError: ns does not exist: growi.users
    at MessageStream.messageHandler (/workspace/growi/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:376:20)
    at processIncomingData (/workspace/growi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/workspace/growi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:745:22)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:4945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yuki-takei** [comment]
# My procedure 2

## mongo1
- Remove ./init.js:/init.js:ro line
    - https://github.com/skomma/growi-docker-compose/blob/master/docker-compose.yml#L53
- Don't run `mongo /init.js`

## src/lib/util/mongoose-utils.js
```
...
const getMongoUri = () => {
  return 'mongodb://mongo1,mongo2,mongo3/growi?replicaSet=rs0&readPreference=secondary';
};
...
```

## Logs

```
node ➜ /workspace/growi (master ✗) $ yarn migrate
yarn run v1.22.5
$ npm run migrate:up
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1623239425226-0.1510074740163876/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> growi@4.2.21-RC migrate:up /workspace/growi
> migrate-mongo up -f config/migrate.js

the options [useFindAndModify] is not supported
11:50:25.906Z  INFO growi:migrate:make-email-unique: Start migration
(node:584) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
11:50:25.946Z  INFO growi:migrate:make-email-unique: Invoking syncIndexes
(node:584) UnhandledPromiseRejectionWarning: MongoError: not master
    at MessageStream.messageHandler (/workspace/growi/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:376:20)
    at processIncomingData (/workspace/growi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/workspace/growi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:745:22)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yuki-takei** [comment]
# My procedure 3

```
yuki@CELIA3:~/Project/GROWI$ git clone https://github.com/skomma/growi-docker-compose growi-replset
Cloning into 'growi-replset'...
remote: Enumerating objects: 644, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 644 (delta 12), reused 14 (delta 4), pack-reused 612
Receiving objects: 100% (644/644), 103.31 KiB | 665.00 KiB/s, done.
Resolving deltas: 100% (341/341), done.
yuki@CELIA3:~/Project/GROWI$ cd growi-replset/
yuki@CELIA3:~/Project/GROWI/growi-replset$ docker compose up mongo1 mongo2 mongo3
[+] Running 11/12
 ⠿ Network growi-replset_default           Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo3_configdb"  Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo3_db"        Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_es_data"          Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_growi_data"       Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo1_configdb"  Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo1_db"        Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo2_configdb"  Created                                                                                                                                                                                            0.0s
 ⠿ Volume "growi-replset_mongo2_db"        Created                                                                                                                                                                                            0.0s
 ⠇ Container growi-replset_mongo1_1        Creating                                                                                                                                                                                           2.9s
 ⠿ Container growi-replset_mongo2_1        Created                                                                                                                                                                                            2.9s
 ⠿ Container growi-replset_mongo3_1        Created                                                                                                                                                                                            2.9s
Error response from daemon: not a directory
```

**Comment by skomma** [comment]
This bug seems to be related to https://jira.mongodb.org/browse/NODE-2784.

The version of mongodb package used by migrate-mongo/mongoose is 3.6.2.

https://github.com/weseek/growi/blob/master/yarn.lock#L9633
https://github.com/weseek/growi/blob/master/yarn.lock#L9979
https://github.com/weseek/growi/blob/master/yarn.lock#L9916-L9917
