### ISSUE TITLE
Bug:Growi Official botによるSlack通知ができない

### ISSUE THREAD

**Issue by matsuzawa-cms** [weseek/growi#4161]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |4.3.2|
|node.js   |14.17.3|
|npm       |6.14.13|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 64bit|
|browser   |Firefox 91.0 64bit|

How to reproduce? (再現手順)
---------------------------

1. Official botのSlack連携を行う
   (連携が成功していることは、連携テストのログおよびSlack側の連携成功メッセージで確認済み)
1. [外部ツールへの通知]-[Global notification]から、通知対象となるパス、トリガーイベント(すべて有効)を登録する
1. 対象パスの記事を投稿/更新する

What happens? (症状)
---------------------

- Growiの記事更新時に、Slackへ通知が飛ばない

以下のエラーログが出力されることを確認。

```
app_1            | [2021-08-18T06:40:57.780Z] ERROR: growi/79 on 4a5be1bcd122:
app_1            |   Unhandled Rejection: Promise: Promise {
app_1            |     <rejected> Error: An API error occurred: not_authed
app_1            |         at Object.platformErrorFromResult (/opt/growi/node_modules/@slack/web-api/dist/errors.js:51:33)
app_1            |         at WebClient.apiCall (/opt/growi/node_modules/@slack/web-api/dist/WebClient.js:157:28)
app_1            |         at runMicrotasks (<anonymous>)
app_1            |         at processTicksAndRejections (internal/process/task_queues.js:95:5)
app_1            |         at async postWithWebApi (/opt/growi/src/server/util/slack.js:23:7) {
app_1            |       code: 'slack_webapi_platform_error',
app_1            |       data: { ok: false, error: 'not_authed', response_metadata: [Object] }
app_1            |     }
app_1            |   } Reason: Error: An API error occurred: not_authed
app_1            |       at Object.platformErrorFromResult (/opt/growi/node_modules/@slack/web-api/dist/errors.js:51:33)
app_1            |       at WebClient.apiCall (/opt/growi/node_modules/@slack/web-api/dist/WebClient.js:157:28)
app_1            |       at runMicrotasks (<anonymous>)
app_1            |       at processTicksAndRejections (internal/process/task_queues.js:95:5)
app_1            |       at async postWithWebApi (/opt/growi/src/server/util/slack.js:23:7) {
app_1            |     code: 'slack_webapi_platform_error',
app_1            |     data: {
app_1            |       ok: false,
app_1            |       error: 'not_authed',
app_1            |       response_metadata: { acceptedScopes: [Array] }
app_1            |     }
app_1            |   }```


What is the expected result? (期待される動作)
-------------------------------------------

- Growiの記事更新時に、Slackへ通知できる


Note
----

- 
-

**Comment by yuki-takei** [comment]
@matsuzawa-cms ご報告ありがとうございます。再現確認しました。
対応を行いますので今しばらくお待ちください。

**Comment by yuki-takei** [comment]
修正完了しました。v4.4.0 リリースをお待ちください。
