### ISSUE TITLE
Bug: GROWI v3.1.1 doesn't post to Slack

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/growi#436]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.3.1611 (Core) |
|GROWI     |3.1.0|
|node.js   |x.y.z ※|
|npm       |x.y.z ※|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

※すみません、現在 v3.0.13 に戻してしまったので、node.js npm の正確なバージョンがわかりません…。

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|browser   |Vivaldi 1.15.1147.42 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1. Slack Incoming Webhooks Configuration を事前に設定しておく
1. GROWI v3.1.0 にアップグレード
1. ページ編集にて slack 通知にチェックをし、チャンネル名を入力して更新する

What happens? (症状)
---------------------

- Slack （当社ではMattermostですが）に更新通知が行われない

What is the expected result? (期待される動作)
-------------------------------------------

- Slack への通知が行われる

Note
----
- GROWI を 3.0.13 から 3.1.0 へバージョンアップしたところ、Slack（当社ではMattermostですが）への通知が行われなくなりました。
- バージョンを 3.0.13 に戻したら通知されるようになりましたので、3.1.0 からの問題かと思います。

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございます。手元で再現確認しました。
次回リリースとなる v3.1.2 で修正予定ですが、再現率が 100% ではないようで、ちょっと手間取るかもしれないです。今しばらくお待ちください。

**Comment by yuki-takei** [comment]
@takuma-watanabe 修正完了しました。次回リリースをお待ちください。

**Comment by takuma-watanabe** [comment]
ありがとうございます。
リリースお待ちしています。

**Comment by yuki-takei** [comment]
v3.1.2 でも直っていないという報告があったので reopen

**Comment by yuki-takei** [comment]
どうやらデモ環境(v3.1.2)でページ編集を行った場合に通知されない模様。

**Comment by yuki-takei** [comment]
demo.growi.org のログ
```
[2018-06-04T07:50:51.852Z] DEBUG: growi:routes:page/30 on bb7694b9c3ac: notify:  { slack: { on: '1', channel: 'general' } }
[2018-06-04T07:50:51.863Z] DEBUG: growi:models:page/30 on bb7694b9c3ac:
  Successfully saved new revision { format: 'markdown',
    createdAt: 2018-06-04T07:50:51.857Z,
    _id: 5b14ef5b7dcdd5001ec68c2a,
    path: '/user/yuki/memo/2018/06/04',
    body: 'test22',
    author: 592f90127f616a0019f77e79,
    __v: 0 }
[2018-06-04T07:50:51.867Z] DEBUG: growi:models:page/30 on bb7694b9c3ac: pushRevision on Update
[2018-06-04T07:50:51.870Z] DEBUG: growi:models:page/30 on bb7694b9c3ac:
  Page.updateGrant, saved grantedUsers. null { status: 'published',
    grant: 1,
    grantedUsers: [],
    liker: [],
    seenUsers: [ 592f90127f616a0019f77e79 ],
    commentCount: 0,
    extended: { slack: 'general' },
    createdAt: 2018-06-04T07:38:23.293Z,
    _id: 5b14ec6f0a7879001f741d43,
    path: '/user/yuki/memo/2018/06/04',
    creator: 592f90127f616a0019f77e79,
    lastUpdateUser: 592f90127f616a0019f77e79,
    updatedAt: 2018-06-04T07:50:51.863Z,
    redirectTo: null,
    __v: 2,
    revision:
     { format: 'markdown',
       createdAt: 2018-06-04T07:50:51.857Z,
       _id: 5b14ef5b7dcdd5001ec68c2a,
       path: '/user/yuki/memo/2018/06/04',
       body: 'test22',
       author: 592f90127f616a0019f77e79,
       __v: 0 },
    id: '5b14ec6f0a7879001f741d43' }
[2018-06-04T07:50:51.877Z] DEBUG: growi:models:page/30 on bb7694b9c3ac:
  Page grant update: { status: 'published',
    grant: 1,
    grantedUsers: [],
    liker: [],
    seenUsers: [ 592f90127f616a0019f77e79 ],
    commentCount: 0,
    extended: { slack: 'general' },
    createdAt: 2018-06-04T07:38:23.293Z,
    _id: 5b14ec6f0a7879001f741d43,
    path: '/user/yuki/memo/2018/06/04',
    creator: 592f90127f616a0019f77e79,
    lastUpdateUser: 592f90127f616a0019f77e79,
    updatedAt: 2018-06-04T07:50:51.863Z,
    redirectTo: null,
    __v: 2,
    revision:
     { format: 'markdown',
       createdAt: 2018-06-04T07:50:51.857Z,
       _id: 5b14ef5b7dcdd5001ec68c2a,
       path: '/user/yuki/memo/2018/06/04',
       body: 'test22',
       author: 592f90127f616a0019f77e79,
       __v: 0 },
    id: '5b14ec6f0a7879001f741d43' }
[2018-06-04T07:50:51.884Z] DEBUG: growi:routes:page/30 on bb7694b9c3ac:
  Page create or edit error. { Error: Cannot find module 'diff'
      at Function.Module._resolveFilename (module.js:547:15)
      at Function.Module._resolveFilename (/opt/growi/node_modules/module-alias/index.js:43:29)
      at Function.Module._load (module.js:474:25)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at prepareAttachmentTextForUpdate (/opt/growi/lib/util/slack.js:55:16)
      at prepareSlackMessage (/opt/growi/lib/util/slack.js:91:14)
      at Object.slack.post (/opt/growi/lib/util/slack.js:135:24)
      at /opt/growi/lib/routes/page.js:667:27
      at Array.map (<anonymous>)
      at /opt/growi/lib/routes/page.js:666:45
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'MODULE_NOT_FOUND' }
[2018-06-04T07:50:51.916Z] DEBUG: growi:routes:page/30 on bb7694b9c3ac: Page found 5b14ec6f0a7879001f741d43 /user/yuki/memo/2018/06/04
[2018-06-04T07:50:58.725Z] DEBUG: growi:routes:page/30 on bb7694b9c3ac: Page list show /
```
