### ISSUE TITLE
カスタマイズ設定を開くと、Internal Server Errorとなる

### ISSUE THREAD

**Issue by nyan-salmon** [weseek/growi#467]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04.4 LTS (Xenial Xerus)|
|GROWI     |3.1.5|
|node.js   |8.11.2|
|npm       |5.10.0|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Microsoft Windows [Version 10.0.17134.81]|
|browser   |Google Chrome 66.0.3359.181（Official Build） （64 ビット）|

How to reproduce? (再現手順)
---------------------------

1. v3.0.10で、設定->カスタマイズ->natureテーマを選択、Update
  テーマは正常に設定されるが、外見はデフォルトのまま
2. 以降のバージョンにアップデート
3. 設定->カスタマイズにアクセス

What happens? (症状)
---------------------

- 設定->カスタマイズを開いたときに、Internal Server Errorと表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- カスタマイズ設定ができる。

Note
----

- v3.0.10に新テーマが選択できないというバグがあり、その設定情報を保持したまま上位バージョンにアップデートしてしまったことが原因？

**Comment by yuki-takei** [comment]
@nyan-salmon 2点追加で情報をいただけますでしょうか。

2. のアップデート時の手順を教えてください。その際、 `npm run build:prod` 時の出力にエラーが出てないかどうか、を教えてください。

カスタマイズページへのアクセス時、サーバー側の出力にエラーが出ていないかどうかを教えてください。

よろしくお願いいたします。

**Comment by nyan-salmon** [comment]
@yuki-takei 
返信ありがとうございます。
以下、回答させていただきます。

## アップデート手順は？
growiのインストールに関しては、こちらの記事を、
* https://qiita.com/SkyLaptor/items/d963157b81a87f3b5726
アップデートに関しては、こちらの記事を、
* https://qiita.com/SkyLaptor/items/70db49b85a3c7a1b3074

参考に行っております。

## npm run build:prod 実行時にエラーが発生するか？
以下、実行時の出力内容です。
```bash
/opt/growi$ sudo npm run build:prod

> growi@3.1.5 prebuild:prod /opt/growi
> npm run plugin:def


> growi@3.1.5 plugin:def /opt/growi
> node bin/generate-plugin-definitions-source.js


> growi@3.1.5 build:prod /opt/growi
> npm run clean && webpack --config config/webpack.prod.js --progress --profile --bail


> growi@3.1.5 clean /opt/growi
> npm-run-all -p clean:*


> growi@3.1.5 clean:js /opt/growi
> rimraf -- public/js


> growi@3.1.5 clean:report /opt/growi
> rimraf -- report


> growi@3.1.5 clean:dll /opt/growi
> rimraf -- public/dll

28254ms building modules
30ms sealing
1ms optimizing
2ms basic module optimization
6ms module optimization
3ms advanced module optimization
13ms basic chunk optimization
0ms chunk optimization
2ms advanced chunk optimization
115305ms building modules
0ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
57ms module reviving
3ms module order optimization
18ms module id optimization
19ms chunk reviving
1ms chunk order optimization
65ms chunk id optimization
2384ms hashing
10ms module assets processing
113ms chunk assets processing
36ms additional chunk assets processing
11ms recording
243455ms additional asset processing
 92% chunk asset optimizationKilled
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! growi@3.1.5 build:prod: `npm run clean && webpack --config config/webpack.prod.js --progress --profile --bail`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the growi@3.1.5 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/***/.npm/_logs/2018-06-11T11_54_43_221Z-debug.log
/opt/growi$ cat /home/***/.npm/_logs/2018-06-11T11_54_43_221Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@5.10.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle growi@3.1.5~prebuild:prod: growi@3.1.5
6 verbose lifecycle growi@3.1.5~prebuild:prod: unsafe-perm in lifecycle true
7 verbose lifecycle growi@3.1.5~prebuild:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/growi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle growi@3.1.5~prebuild:prod: CWD: /opt/growi
9 silly lifecycle growi@3.1.5~prebuild:prod: Args: [ '-c', 'npm run plugin:def' ]
10 silly lifecycle growi@3.1.5~prebuild:prod: Returned: code: 0  signal: null
11 info lifecycle growi@3.1.5~build:prod: growi@3.1.5
12 verbose lifecycle growi@3.1.5~build:prod: unsafe-perm in lifecycle true
13 verbose lifecycle growi@3.1.5~build:prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/growi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
14 verbose lifecycle growi@3.1.5~build:prod: CWD: /opt/growi
15 silly lifecycle growi@3.1.5~build:prod: Args: [ '-c',
15 silly lifecycle   'npm run clean && webpack --config config/webpack.prod.js --progress --profile --bail' ]
16 silly lifecycle growi@3.1.5~build:prod: Returned: code: 137  signal: null
17 info lifecycle growi@3.1.5~build:prod: Failed to exec build:prod script
18 verbose stack Error: growi@3.1.5 build:prod: `npm run clean && webpack --config config/webpack.prod.js --progress --profile --bail`
18 verbose stack Exit status 137
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid growi@3.1.5
20 verbose cwd /opt/growi
21 verbose Linux 4.4.0-124-generic
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prod"
23 verbose node v8.11.2
24 verbose npm  v5.10.0
25 error code ELIFECYCLE
26 error errno 137
27 error growi@3.1.5 build:prod: `npm run clean && webpack --config config/webpack.prod.js --progress --profile --bail`
27 error Exit status 137
28 error Failed at the growi@3.1.5 build:prod script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 137, true ]
/opt/growi$
```

## カスタマイズページへのアクセス時、サーバー側の出力にエラーが出ていないか
上のコマンドを実行すると、正常に起動できなくなったため、検証不可能です。

バックアップからリカバリを行い、同様の症状が見られれば追記させていただきます。

**Comment by yuki-takei** [comment]
@nyan-salmon やはりビルド中にエラーが出ていますね。しかも結構後半まで処理が進んでいますので、途中でなにかが足りないとかではないようです。

核心となるメッセージがないので結局何が悪いのかは想像でしかないのですが、マシンのメモリは足りていますか？

**Comment by nyan-salmon** [comment]
@yuki-takei 
Wiki単体であれば問題ないレベルですが、メモリ不足であればGitLabが裏方で動いているのが原因かもしれません。

現在リカバリ作業中で、ビルド時に同様のエラーが出た場合検証してみます。

**Comment by nyan-salmon** [comment]
@yuki-takei 
只今、リカバリ作業が終わりました。

上のエラーはやはり、GitLabによるメモリ不足が原因のようでした。
GitLabを一度stopし、再度ビルドを行ったところ正常終了しました。

また、今回のIssueに関するエラーは、アップデート時にbuildを行っていなかったのが原因でした。
お騒がせして申し訳ありません。また、丁寧に対応くださり非常に助かりました。

今後とも、よろしくお願いいたします。
