### ISSUE TITLE
Bug: v4.4.11及びv4.4.12のローカル環境で正常に起動できない

### ISSUE THREAD

**Issue by hanapage** [weseek/growi#4685]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu Server 20.04.3 LTS|
|GROWI     |4.4.10|
|node.js   |14.18.1|
|npm       |6.14.15|
|yarn      |1.22.15|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10 Pro 21H1 |
|browser   |Google Chrome 96.0.4664.45|

How to reproduce? (再現手順)
---------------------------
- npx lerna bootstrapを実行する
- npm startで起動する

What happens? (症状)
---------------------

- 大量のログが表示され、エラーで終了する (下記はv4.4.12のログです)
  
  ```sh
  # ～～前略～～
  $ yarn cp:public && yarn cp:views && yarn cp:bootstrap
  $ cp -RT ./src/public ./dist/public
  $ cp -RT ./src/views ./dist/views
  $ cp -RT ./node_modules/bootstrap/dist ./dist/public/bootstrap
  lerna ERR! yarn run build exited 1 in '@growi/app'
  lerna ERR! yarn run build stdout:
  $ yarn cross-env NODE_ENV=production run-p clean resources:*
  $ /opt/growi/node_modules/.bin/cross-env NODE_ENV=production run-p clean 'resources:*'
  
  > @growi/app@4.4.12 resources:plugin /opt/growi/packages/app
  > yarn ts-node bin/generate-plugin-definitions-source.ts
  
  # ～～中略～～
  <--- Last few GCs --->
  
  [25989:0x63bd7c0]    99355 ms: Mark-sweep 959.0 (1006.1) -> 951.6 (1006.9) MB, 1212.5 / 0.0 ms  (average mu = 0.150, current mu = 0.070) allocation failure scavenge might not succeed
  [25989:0x63bd7c0]   100606 ms: Mark-sweep 960.1 (1006.9) -> 952.6 (1008.6) MB, 1188.6 / 0.0 ms  (average mu = 0.103, current mu = 0.050) allocation failure scavenge might not succeed
  
  
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xa389b0 node::Abort() [/usr/bin/node]
   2: 0x96e0af node::FatalError(char const*, char const*) [/usr/bin/node]
   3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   5: 0xd73fd5  [/usr/bin/node]
   6: 0xd74b5f  [/usr/bin/node]
   7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
   8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
   9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
  10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
  11: 0x1446379  [/usr/bin/node]
  
  <--- Last few GCs --->
  
  [26018:0x58977c0]    98699 ms: Mark-sweep 959.7 (1005.6) -> 952.2 (1007.1) MB, 1237.6 / 0.0 ms  (average mu = 0.197, current mu = 0.051) allocation failure scavenge might not succeed
  [26018:0x58977c0]    99975 ms: Mark-sweep 960.6 (1007.1) -> 953.3 (1008.9) MB, 1175.8 / 0.0 ms  (average mu = 0.142, current mu = 0.079) allocation failure scavenge might not succeed
  
  
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xa389b0 node::Abort() [/usr/bin/node]
   2: 0x96e0af node::FatalError(char const*, char const*) [/usr/bin/node]
   3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   5: 0xd73fd5  [/usr/bin/node]
   6: 0xd74b5f  [/usr/bin/node]
   7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
   8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
   9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
  10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
  11: 0x1446379  [/usr/bin/node]
  
  <--- Last few GCs --->
  
  [26027:0x46ed7c0]   102104 ms: Scavenge (reduce) 958.4 (994.9) -> 957.6 (995.9) MB, 7.3 / 0.0 ms  (average mu = 0.199, current mu = 0.179) allocation failure
  [26027:0x46ed7c0]   102121 ms: Scavenge (reduce) 958.5 (994.9) -> 957.8 (996.1) MB, 11.5 / 0.0 ms  (average mu = 0.199, current mu = 0.179) allocation failure
  [26027:0x46ed7c0]   103373 ms: Mark-sweep (reduce) 958.7 (995.1) -> 957.5 (996.1) MB, 1238.0 / 0.0 ms  (average mu = 0.142, current mu = 0.081) allocation failure scavenge might not succeed
  
  
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xa389b0 node::Abort() [/usr/bin/node]
   2: 0x96e0af node::FatalError(char const*, char const*) [/usr/bin/node]
   3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   5: 0xd73fd5  [/usr/bin/node]
   6: 0xd74b5f  [/usr/bin/node]
   7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
   8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
   9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
  10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
  11: 0x1446379  [/usr/bin/node]
  
  <--- Last few GCs --->
  
  [26036:0x64757c0]   100672 ms: Mark-sweep 962.4 (1007.9) -> 954.2 (1008.1) MB, 1293.4 / 0.0 ms  (average mu = 0.106, current mu = 0.046) allocation failure scavenge might not succeed
  [26036:0x64757c0]   101973 ms: Mark-sweep 962.7 (1008.4) -> 955.1 (1009.6) MB, 1195.2 / 0.0 ms  (average mu = 0.094, current mu = 0.081) allocation failure scavenge might not succeed
  
  
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xa389b0 node::Abort() [/usr/bin/node]
   2: 0x96e0af node::FatalError(char const*, char const*) [/usr/bin/node]
   3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
   5: 0xd73fd5  [/usr/bin/node]
   6: 0xd74b5f  [/usr/bin/node]
   7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
   8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
   9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
  10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
  11: 0x1446379  [/usr/bin/node]
  error Command failed with exit code 2.
  npm ERR! code ELIFECYCLE
  npm ERR! errno 2
  npm ERR! @growi/app@4.4.12 build:client: `yarn cross-env NODE_ENV=production webpack --config config/webpack.prod.js --profile --bail`
  npm ERR! Exit status 2
  npm ERR!
  npm ERR! Failed at the @growi/app@4.4.12 build:client script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2021-11-17T06_37_19_694Z-debug.log
  ERROR: "build:client" exited with 2.
  error Command failed with exit code 1.
  lerna ERR! yarn run build exited 1 in '@growi/app'
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! growi@4.4.12 prestart: `yarn app:build`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the growi@4.4.12 prestart script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2021-11-17T06_37_20_574Z-debug.log
  ```

What is the expected result? (期待される動作)
-------------------------------------------

- GROWIが正常に起動する

Note
----
 
- `/root/.npm/_logs/2021-11-17T06_37_19_694Z-debug.log`の中身
  
  ```sh
  0 info it worked if it ends with ok
  1 verbose cli [
  1 verbose cli   '/usr/bin/node',
  1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
  1 verbose cli   'run',
  1 verbose cli   'build:client'
  1 verbose cli ]
  2 info using npm@6.14.15
  3 info using node@v14.18.1
  4 verbose run-script [ 'prebuild:client', 'build:client', 'postbuild:client' ]
  5 info lifecycle @growi/app@4.4.12~prebuild:client: @growi/app@4.4.12
  6 info lifecycle @growi/app@4.4.12~build:client: @growi/app@4.4.12
  7 warn lifecycle The node binary used for scripts is /tmp/yarn--1637130501713-0.01890722985009452/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
  8 verbose lifecycle @growi/app@4.4.12~build:client: unsafe-perm in lifecycle true
  9 verbose lifecycle @growi/app@4.4.12~build:client: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/growi/packages/app/node_modules/.bin:/tmp/yarn--1637130501713-0.01890722985009452:/opt/growi/packages/app/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/opt/growi/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/tmp/yarn--1637130456077-0.6242133120287114:/opt/growi/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/opt/growi/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/tmp/yarn--1637130455758-0.8160627585790368:/opt/growi/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/opt/growi/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/growi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  10 verbose lifecycle @growi/app@4.4.12~build:client: CWD: /opt/growi/packages/app
  11 silly lifecycle @growi/app@4.4.12~build:client: Args: [
  11 silly lifecycle   '-c',
  11 silly lifecycle   'yarn cross-env NODE_ENV=production webpack --config config/webpack.prod.js --profile --bail'
  11 silly lifecycle ]
  12 silly lifecycle @growi/app@4.4.12~build:client: Returned: code: 2  signal: null
  13 info lifecycle @growi/app@4.4.12~build:client: Failed to exec build:client script
  14 verbose stack Error: @growi/app@4.4.12 build:client: `yarn cross-env NODE_ENV=production webpack --config config/webpack.prod.js --profile --bail`
  14 verbose stack Exit status 2
  14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
  14 verbose stack     at EventEmitter.emit (events.js:400:28)
  14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
  14 verbose stack     at ChildProcess.emit (events.js:400:28)
  14 verbose stack     at maybeClose (internal/child_process.js:1058:16)
  14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
  15 verbose pkgid @growi/app@4.4.12
  16 verbose cwd /opt/growi/packages/app
  17 verbose Linux 5.4.0-90-generic
  18 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "build:client"
  19 verbose node v14.18.1
  20 verbose npm  v6.14.15
  21 error code ELIFECYCLE
  22 error errno 2
  23 error @growi/app@4.4.12 build:client: `yarn cross-env NODE_ENV=production webpack --config config/webpack.prod.js --profile --bail`
  23 error Exit status 2
  24 error Failed at the @growi/app@4.4.12 build:client script.
  24 error This is probably not a problem with npm. There is likely additional logging output above.
  25 verbose exit [ 2, true ]
  ```
- `/root/.npm/_logs/2021-11-17T06_37_20_574Z-debug.log`の中身
  
  ```sh
  0 info it worked if it ends with ok
  1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
  2 info using npm@6.14.15
  3 info using node@v14.18.1
  4 verbose run-script [ 'prestart', 'start', 'poststart' ]
  5 info lifecycle growi@4.4.12~prestart: growi@4.4.12
  6 verbose lifecycle growi@4.4.12~prestart: unsafe-perm in lifecycle true
  7 verbose lifecycle growi@4.4.12~prestart: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp- 
  bin:/opt/growi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  8 verbose lifecycle growi@4.4.12~prestart: CWD: /opt/growi
  9 silly lifecycle growi@4.4.12~prestart: Args: [ '-c', 'yarn app:build' ]
  10 silly lifecycle growi@4.4.12~prestart: Returned: code: 1  signal: null
  11 info lifecycle growi@4.4.12~prestart: Failed to exec prestart script
  12 verbose stack Error: growi@4.4.12 prestart: `yarn app:build`
  12 verbose stack Exit status 1
  12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
  12 verbose stack     at EventEmitter.emit (events.js:400:28)
  12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
  12 verbose stack     at ChildProcess.emit (events.js:400:28)
  12 verbose stack     at maybeClose (internal/child_process.js:1058:16)
  12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
  13 verbose pkgid growi@4.4.12
  14 verbose cwd /opt/growi
  15 verbose Linux 5.4.0-90-generic
  16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
  17 verbose node v14.18.1
  18 verbose npm  v6.14.15
  19 error code ELIFECYCLE
  20 error errno 1
  21 error growi@4.4.12 prestart: `yarn app:build`
  21 error Exit status 1
  22 error Failed at the growi@4.4.12 prestart script.
  22 error This is probably not a problem with npm. There is likely additional logging output above.
  23 verbose exit [ 1, true ]
  ```

**Comment by hanapage** [comment]
v4.4.13でも同様の症状が発生しましたが起動時のオプションに

```bash
NODE_OPTIONS=--max-old-space-size=2048
```

を追加することで解決しました。デフォルト？の設定だとメモリが不足するようです。

**Comment by yuki-takei** [comment]
@hanapage 報告ありがとうございます。とはいえこれは環境に依って陥る問題でバグとは言えないと思いますので、そういうワークアラウンドで回避するという話になると思います。

詳細に説明いただけたのはとても助かります。

**Comment by yuki-takei** [comment]
対策も書かれていますのでクローズします。
