### ISSUE TITLE
HackMD編集時にエラーが発生

### ISSUE THREAD

**Issue by zsh2fish** [weseek/growi#598]
### Host

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.6|
|GROWI     |3.2.1|
|node.js   |8.11.4|
|npm       |5.6.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |macOS High Sierra 10.13.6|
|browser   |Google Chrome 68.0.3440.106|

How to reproduce? (再現手順)
---------------------------

1. `git clone https://github.com/weseek/growi-docker-compose.git`
2. `cd growi-docker-compose/`
3. `cp examples/integrate-with-hackmd/docker-compose.override.yml .` そして編集
```diff
[yamaki growi-docker-compose]$ diff examples/integrate-with-hackmd/docker-compose.override.yml docker-compose.override.yml
12c12
<       - GROWI_URI=http://CHANGE-HERE
---
>       - GROWI_URI=http://localhost:3000
```
4. docker-compose.ymlを編集
```diff
[yamaki growi-docker-compose]$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 992deb2..8f1fb64 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,10 +17,10 @@ services:
       - MONGO_URI=mongodb://mongo:27017/growi
       - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
       - PASSWORD_SEED=changeme
-      # - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
-      # - MATHJAX=1             # activate this line if you want to use MathJax
-      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
-      # - HACKMD_URI=http://    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
+      - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
+      - MATHJAX=1             # activate this line if you want to use MathJax
+      - PLANTUML_URI=http://localhost:13080/ # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
+      - HACKMD_URI=http://127.0.0.1:3100    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
       # - HACKMD_URI_FOR_SERVER=http://hackmd:3000  # activate this line and specify HackMD server URI which can be accessed from this server container

     command: "dockerize
```
5. `docker-compose up` で起動
6. ブラウザで localhost:3100 にアクセスしHackMDの起動を確認
7. ブラウザで localhost:3000 にアクセスしGROWIの起動を確認
8. ログイン後、 /Sandbox で 「Start to edit with HackMD」ボタンを押下

What happens? (症状)
---------------------
- ブラウザ上で「Error Occured Integration with Hack MD process failed」が表示される
- docker-composeのコンソール上で以下が表示される
```
app_1            | [2018-09-02T12:08:59.994Z]  INFO: express/43 on b1f427517e86: ::ffff:172.23.0.1 <-- GET /_api/attachments.list?page_id=5b4ad076b600b200280d601d HTTP/1.1 200 28 http://localhost:3000/Sandbox Chrome 68.0 Mac OS X 10.13.6 6.5721 ms (req_id=354a1a24-41bc-44db-a43b-18dd095bbb30)
app_1            | [2018-09-02T12:09:03.497Z] ERROR: growi:routes:hackmd/43 on b1f427517e86: connect ECONNREFUSED 127.0.0.1:3100
app_1            |   Error: connect ECONNREFUSED 127.0.0.1:3100
app_1            |       at Object._errnoException (util.js:992:11)
app_1            |       at _exceptionWithHostPort (util.js:1014:20)
app_1            |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
app_1            | [2018-09-02T12:09:03.503Z]  INFO: express/43 on b1f427517e86: ::ffff:172.23.0.1 <-- POST /_api/hackmd.integrate HTTP/1.1 200 61 http://localhost:3000/Sandbox Chrome 68.0 Mac OS X 10.13.6 9.1515 ms (req_id=37de8779-e0cb-471f-9875-cafae6b36ed4)
```

What is the expected result? (期待される動作)
-------------------------------------------

- HackMDで編集できる

Note
----

- 特になし

**Comment by yuki-takei** [comment]
@zsh2fish `HACKMD_URI_FOR_SERVER` の設定を見直してみてください。
「app (GROWI) コンテナからアクセス可能な HackMD (コンテナ)の URK」になります。指定しない場合は `HACKMD_URI` と同じ値を利用しますが、growi-docker-compose を使っていると思いますので、ここは

> # - HACKMD_URI_FOR_SERVER=http://hackmd:3000

をコメントアウトするだけでいいと思います。

**Comment by zsh2fish** [comment]
ありがとうございます。

> HACKMD_URI_FOR_SERVER=http://hackmd:3000

にて無事、動作を確認できました！
