### ISSUE TITLE
Bug: 'Update and overwrite scopes of all descendants' does not work

### ISSUE THREAD

**Issue by yuki-takei** [weseek/growi#6799]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu|
|GROWI     |5.1.6|
|node.js   |16.18.0|
|npm       |8.19.2|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Win 11|
|browser   |Firefox|

How to reproduce? (再現手順)
---------------------------

1. Open `/Sandbox`
2. Set `Only me` and save with 'Update and overwrite scopes of all descendants'
    ![image](https://user-images.githubusercontent.com/1638767/197126630-b4e19441-569a-4ba6-a3f7-69c9d0a8986c.png)

What happens? (症状)
---------------------

- Couldn't save with an error

```
06:19:03.276Z ERROR growi:routes:page:
  error on _api/pages.update Error: The selected grant or grantedGroup is not assignable to this page.
      at Function.schema.statics.updatePage (/workspace/growi/packages/app/src/server/models/page.ts:1019:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at api.update (/workspace/growi/packages/app/src/server/routes/page.js:1025:14)
```

What is the expected result? (期待される動作)
-------------------------------------------

- Saved successfully
- Show toastr if the operation is failed

**Comment by yuki-takei** [comment]
## Note
`processValidation` の
```
      if (descendants.isPublicExist) { // public page must not exist under GRANT_OWNER page
        return false;
      }
```
で、子孫ページを判定する際に false を返してしまう
