### ISSUE TITLE
Bug: Cannot "overwrite scope," no error shown on the browser

### ISSUE THREAD

**Issue by nandnor93** [weseek/growi#6821]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu Server 20.04 LTS |
|GROWI     |5.1.6|
|node.js   |16.18.0|
|npm       |8.19.2|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Monterey 12.5 |
|browser   | Google Chrome 106.0.5249.119  |

How to reproduce? (再現手順)
---------------------------

1. Clone the official docker-compose repo [growi-docker-compose]
1. Change only the `ports` and `volumes` directives in `docker-compose.yml`
1. Build and start the container
    ```bash
    docker-compose up
    ```
1. Sign up for the newly built GROWI as user `admin`
1. Navigate to the *App Settings* and set the *Site URL* (ONLY; no other settings are changed)
1. Create a group named `testgrp` in *UserGroup Management*
1. Add `admin` user to the group
1. Create a page `/test_upd_priv` as a *Public* page
1. Create child pages `/test_upd_priv/test01` and `/test_upd_priv/test02` as *Public* pages
1. Enter the edit page of `/test_upd_priv`, select *Only inside a group* and choose `testgrp`, and click *Update and overwrite scopes of all descendants*

What happens? (症状)
---------------------

- **No response is seen, and no error popups are shown on the browser**. Only the app log on Docker says:

```
app_1            | {"name":"growi:routes:page","hostname":"******","pid":18,"level":50,"msg":"error on _api/pages.update Error: The selected grant or grantedGroup is not assignable to this page.\n    at Function.schema.statics.updatePage (/opt/growi/packages/app/dist/server/models/page.js:752:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async api.update (/opt/growi/packages/app/dist/server/routes/page.js:878:20)","time":"2022-10-24T10:14:29.571Z","v":0}
app_1            | {"name":"express","hostname":"******","pid":18,"req_id":"292d4bca-d162-4603-bf5e-12267cfe3cae","level":30,"msg":"::ffff:192.168.2.102 <-- POST /_api/pages.update HTTP/1.1 200 96 http://******:3002/635662d462ae8e0bb6811dab Chrome 106.0 Mac OS X 10.15.7 35.986948 ms","time":"2022-10-24T10:14:29.574Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

- The page and its child pages are successfully updated to become group-only pages
- If some problems should occur, a red error popup is shown on the browser.

**Comment by nandnor93** [comment]
Duplicate of #6799
