### ISSUE TITLE
Bug: "Cannot find module 'stream-to-promise'" occured when FILE_UPLOAD=local

### ISSUE THREAD

**Issue by moochannel** [weseek/growi#857]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.1 LTS|
|GROWI     |3.4.0|
|node.js   |10.15.2|
|npm       |6.4.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Google Chrome 72.0.3626.119|

How to reproduce? (再現手順)
---------------------------

[Upgrading to GROWI v3.4.x](https://docs.growi.org/guide/upgrading/34x.html#the-case-using-on-premise)を参照して3.4.0にアップグレードしました。

1. GROWI(3.3系)を停止
    ```bash
    docker-compose down
    ```
1. growi-docker-composeを更新
    ```bash
    git fetch --prune
    git pull
    vi docker-compose.yml  (HackMDに関する項目を追加)
    ```
1. Elasticsearchのボリュームを削除
    ```bash
    docker volume rm growi_es_data
    docker volume rm growi_es_plugins
    ```
1. GROWI(3.4系)をビルド、実行
    ```bash
    docker-compose build --pull
    docker-compose pull
    docker-compose up -d
    ```
1. GROWIコンテナのログを確認
    ```bash
    docker-compose logs -f app
    ```

What happens? (症状)
---------------------

- appコンテナが起動途中でエラーログを出力して異常終了します
```
> growi@3.4.0 server:prod /opt/growi
> env-cmd config/env.prod.js node src/server/app.js

[2019-03-05T03:44:40.504Z] ERROR: growi/65 on 408941b88d95: An error occurred, unable to start the server
[2019-03-05T03:44:40.506Z] ERROR: growi/65 on 408941b88d95: Cannot find module 'stream-to-promise'
  Error: Cannot find module 'stream-to-promise'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._resolveFilename (/opt/growi/node_modules/module-alias/index.js:43:29)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (/opt/growi/src/server/service/file-uploader/local.js:6:25)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at FileUploaderFactory.getUploader (/opt/growi/src/server/service/file-uploader/index.js:16:23)
      at module.exports (/opt/growi/src/server/service/file-uploader/index.js:26:18)
      at Object.module.exports [as Attachment] (/opt/growi/src/server/models/attachment.js:9:59)
      at /opt/growi/src/server/crowi/index.js:212:34
      at Array.forEach (<anonymous>)
      at /opt/growi/src/server/crowi/index.js:211:25
      at new Promise (<anonymous>)
      at Crowi.setupModels (/opt/growi/src/server/crowi/index.js:210:10)
      at Crowi.init (/opt/growi/src/server/crowi/index.js:75:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! growi@3.4.0 server:prod: `env-cmd config/env.prod.js node src/server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the growi@3.4.0 server:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-05T03_44_40_522Z-debug.log
2019/03/05 03:44:40 Command exited with error: exit status 1
```

What is the expected result? (期待される動作)
-------------------------------------------

- appコンテナが正常に起動する

Note
----

- growi-docker-composeにあるDockerfileを編集し、`stream-to-promise`をインストールするとDockerイメージのビルド中に警告は出ますがappコンテナは起動します。
```diff
diff --git a/Dockerfile b/Dockerfile
index b9d1875..296b993 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -12,6 +12,8 @@ RUN apk add --no-cache --virtual .dl-deps curl \

 WORKDIR ${APP_DIR}

+RUN yarn add stream-to-promise
+
 # install plugins if necessary
 # ;;
 # ;; NOTE: In GROWI v3 and later,
```
(ビルド中のwarning)
```
[5/5] Building fresh packages...
success Saved lockfile.
warning "stream-to-promise" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies". success Saved 1 new dependency.
info Direct dependencies
└─ stream-to-promise@2.2.0
info All dependencies
└─ stream-to-promise@2.2.0
Done in 93.23s.
Removing intermediate container 173a9c9178d6
 ---> 0857910be832
Successfully built 0857910be832
```

**Comment by yuki-takei** [comment]
@moochannel ご報告ありがとうございます。
現状こちらで再現は確認できていないのですが、もしかすると `FILE_UPLOAD=local` 設定または `NO_CDN=true` の環境でのみ発生する事象なのかもしれない、という疑いがあります。

docker-compose.yml で指定している環境変数をいただけますでしょうか。

よろしくお願いいたします。

**Comment by moochannel** [comment]
@yuki-takei ご返信いただきありがとうございます。
docker-compose.yml内で指定している環境変数は下記のとおりです。
```
- TZ=Asia/Tokyo
- MONGO_URI=mongodb://mongo:27017/growi
- ELASTICSEARCH_URI=http://elasticsearch:9200/growi
- PASSWORD_SEED=xxxxx
- FILE_UPLOAD=local
- MATHJAX=1
# - PLANTUML_URI=http://
- HACKMD_URI=https://hackmd.xxx.yyy.zzz
- HACKMD_URI_FOR_SERVER=http://hackmd:3000
```

`NO_CDN=true`は明示していませんが`FILE_UPLOAD=local`は指定しているという状態です。

**Comment by yuki-takei** [comment]
v3.4.1 で対応しました

**Comment by moochannel** [comment]
ありがとうございます!
