### ISSUE TITLE
Growi v3.4.1 doesn't nofity to Slack

### ISSUE THREAD

**Issue by entertvl** [weseek/growi#861]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Alpine |
|GROWI     | 3.4.1 |
|node.js   | 10.15.2 |
|npm       | 6.4.1 |
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]| no |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS Mojave |
|browser   | Safari 12.0.3 |

How to reproduce? (再現手順)
---------------------------

1. Growi の管理ページに有効な Slack Incoming Webhook URL を設定しておく
2. Growi に新規投稿を作成する
3. Slack 通知のチェックボックスにチェックを入れる
4. 作成ボタンを押下後、Slack の通知されるチャンネルを確認する

What happens? (症状)
---------------------

- 投稿時に Slack チャンネルにポストされない

```
[2019-03-07T04:51:06.324Z]  INFO: express/93 on e1fb96607515: ::ffff:172.26.0.1 <-- POST /_api/pages.create HTTP/1.1 200 766 http://localhost:3000/test Safari 12.0 Mac OS X 10.14.3 31.08 ms (req_id=578983e1-e16f-44e7-94a5-e79762493110)
[2019-03-07T04:51:06.338Z] ERROR: growi/93 on e1fb96607515:
  Unhandled Rejection: Promise: Promise {
    <rejected> TypeError: crowi.slack.postPage is not a function
        at /opt/growi/src/server/routes/page.js:97:28
        at Array.map (<anonymous>)
        at notifyToSlackByUser (/opt/growi/src/server/routes/page.js:96:49)
        at process._tickCallback (internal/process/next_tick.js:68:7) } Reason: TypeError: crowi.slack.postPage is not a function
      at /opt/growi/src/server/routes/page.js:97:28
      at Array.map (<anonymous>)
      at notifyToSlackByUser (/opt/growi/src/server/routes/page.js:96:49)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

What is the expected result? (期待される動作)
-------------------------------------------

- Slack に通知がされる

**Comment by yusuketk** [comment]
How to reproduce?(再現手順)の通りに実行したところ、以下のようなエラーログにて同様の症状を確認しました。
```
10:33:29.344Z ERROR growi:
  Unhandled Rejection: Promise: Promise {
    <rejected> TypeError: Url must be a string. Received 5c80d0003eb13c409f270b42
      at normalize (/Users/takizawayuusuke/growi/node_modules/url-join/lib/url-join.js:27:15)
      at /Users/takizawayuusuke/growi/node_modules/url-join/lib/url-join.js:70:12
      at prepareSlackMessageForPage (/Users/takizawayuusuke/growi/src/server/util/slack.js:131:19)
      at Object.slack.postPage (/Users/takizawayuusuke/growi/src/server/util/slack.js:200:24)
      at /Users/takizawayuusuke/growi/src/server/routes/page.js:97:28
      at Array.map (<anonymous>)
      at notifyToSlackByUser (/Users/takizawayuusuke/growi/src/server/routes/page.js:96:49)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7) } Reason: TypeError: Url must be a string. Received 5c80f41dded2e04a326522e7
      at normalize (/Users/takizawayuusuke/growi/node_modules/url-join/lib/url-join.js:27:15)
      at /Users/takizawayuusuke/growi/node_modules/url-join/lib/url-join.js:70:12
      at prepareSlackMessageForPage (/Users/takizawayuusuke/growi/src/server/util/slack.js:131:19)
      at Object.slack.postPage (/Users/takizawayuusuke/growi/src/server/util/slack.js:200:24)
      at /Users/takizawayuusuke/growi/src/server/routes/page.js:97:28
      at Array.map (<anonymous>)
      at notifyToSlackByUser (/Users/takizawayuusuke/growi/src/server/routes/page.js:96:49)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
これに対し修正を行なった結果、What is the expected result?(期待される動作) に記載してある動作を確認したため、本投稿の症状は再現できませんでした。
上記の修正を反映およびデバッグログを追加した v3.4.2 にて、再度同様の症状を確認した場合、再度こちらにログを貼ってください。

**Comment by entertvl** [comment]
@yusuketk v3.4.2 で問題なく通知されました、対応ありがとうございました！
