### ISSUE TITLE
[7.x] Elasticsearchのインデックスのリビルドが途中で進捗しなくなる

### ISSUE THREAD

**Issue by soon624** [weseek/growi#9382]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux2|
|GROWI     |7.1.0|
|node.js   |20.18.0|
|npm       |10.8.2|
|pnpm      |9.12.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 11 Pro |
|browser   |Chrome|

How to reproduce? (再現手順)
---------------------------

1. インデックスのリビルドを実行
全文検索管理 > Elasticsearch 管理 > インデックスのリビルド

What happens? (症状)
---------------------------

進捗が途中で停止する。
「インデックスの正規化」を実行後に再度「インデックスのリビルド」を実行すると、3200/5000 のように毎回同じ進捗で停止する。
このとき、docker logsで以下のようなエラーが取得できる。

```
{"name":"growi","hostname":"5d38b8177554","pid":1,"level":50,"msg":"Unhandled Rejection: Promise: Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'map')
      at ElasticsearchDelegator.generateDocContentsRelatedToRestriction (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:285:50)
      at ElasticsearchDelegator.prepareBodyForCreate (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:314:21)
      at /opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:406:34
      at Array.forEach (<anonymous>)
      at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:405:23)
      at doWrite (node:internal/streams/writable:596:12)
      at clearBuffer (node:internal/streams/writable:781:7)
      at onwrite (node:internal/streams/writable:651:7)
      at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:432:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} Reason: TypeError: Cannot read properties of null (reading 'map')
    at ElasticsearchDelegator.generateDocContentsRelatedToRestriction (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:285:50)
    at ElasticsearchDelegator.prepareBodyForCreate (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:314:21)
    at /opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:406:34
    at Array.forEach (<anonymous>)
    at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:405:23)
    at doWrite (node:internal/streams/writable:596:12)
    at clearBuffer (node:internal/streams/writable:781:7)
    at onwrite (node:internal/streams/writable:651:7)
    at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:432:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","time":"2024-11-11T12:46:29.103Z","v":0}
```

What is the expected result? (期待される動作)
-------------------------------------------

- 途中で停止せずに完了する
- あるいは、是正すべき内容が提示される

Note
----

- なにかがnullになっているため発生している事象だと思いますが、どのデータを修正すればよいかを調べる方法などはありますでしょうか？

**Comment by soon624** [comment]
@yuki-takei さん、ありがとうございます。

ダウングレードは行っていませんが、`20231223155127-non-null-granted-groups.js`を削除した上で再起動してみたところ・・・依然、同じ進捗でインデックスのリビルドが停止してしまいます。

以下のように2024-11-13T12:41:34(日本時間の21:41頃)、non-null-granted-groupsが正常に適用されたことがログに残りますが、

```bash
{"name":"growi:non-null-granted-groups","hostname":"5d38b8177554","pid":26,"level":30,"msg":"Apply migration","time":"2024-11-13T12:41:34.869Z","v":0}
{"name":"growi:non-null-granted-groups","hostname":"5d38b8177554","pid":26,"level":30,"msg":"Migration has successfully applied","time":"2024-11-13T12:41:34.940Z","v":0}
MIGRATED UP: 20231223155127-non-null-granted-groups.js
(node:1) [MONGOOSE] DeprecationWarning: Mongoose: the strictQuery option will be switched back to false by default in Mongoose 7. Use mongoose.set('strictQuery', false); if you want to prepare for this change. Or use mongoose.set('strictQuery', true); to suppress this warning.
(Use node --trace-deprecation ... to show where the warning was created)

```

続けてリビルドを実行すると、リビルドの進捗が途中で停止し、以下のログが出力されます。

```bash
{"name":"growi","hostname":"5d38b8177554","pid":1,"level":50,"msg":"Unhandled Rejection: Promise: Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'map')
      at ElasticsearchDelegator.generateDocContentsRelatedToRestriction (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:285:50)
      at ElasticsearchDelegator.prepareBodyForCreate (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:314:21)
      at /opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:406:34
      at Array.forEach (<anonymous>)
      at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:405:23)
      at writeOrBuffer (node:internal/streams/writable:570:12)
      at _write (node:internal/streams/writable:499:10)
      at Writable.write (node:internal/streams/writable:508:10)
      at Transform.ondata (node:internal/streams/readable:1007:22)
      at Transform.emit (node:events:519:28)
} Reason: TypeError: Cannot read properties of null (reading 'map')
    at ElasticsearchDelegator.generateDocContentsRelatedToRestriction (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:285:50)
    at ElasticsearchDelegator.prepareBodyForCreate (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:314:21)
    at /opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:406:34
    at Array.forEach (<anonymous>)
    at Writable.write [as _write] (/opt/growi/apps/app/dist/server/service/search-delegator/elasticsearch.js:405:23)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Transform.ondata (node:internal/streams/readable:1007:22)
    at Transform.emit (node:events:519:28)","time":"2024-11-13T12:49:30.735Z","v":0}

```

**Comment by soon624** [comment]
ありがとうございます。
grantedUsers が null のページがいくつかありました。これらを是正したうえでインデックスのリビルドを試してみます。
結果はまた報告するようにいたします。

**Comment by soon624** [comment]
@yuki-takei さん、ご助言、ありがとうございました。
grantedUsers が null のページを解消することでElasticsearchのインデックスのリビルドが完了するようになり、私の問題は解消いたしました。

既に削除済みのユーザーが、削除される前に作成したページのgrantedUsers が null になっていたようです。

**Comment by kometchtech** [comment]
> さっきのシナリオは飽くまでも推測でしかないです。 エラーが出ている箇所は同じだと思うので、そうすると grantedUsers の方に問題があるのかもしれません。
> 
> pages collection の中で grantedUsers または grantedGroups が存在しないか null のデータがないか確認してみてください。

コチラの件について、当方も発生しており本issueを発見しました。
mongoでの是正を行う必要があるようですが、当方mongoに理解が無く対応するためのコマンドなどを共有いただけますと助かります。

| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |7.1.0|
|node.js   |20.18.0|
|npm       |10.8.2|
|pnpm      |9.12.3|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

**Comment by soon624** [comment]
手っ取り早いのは、pageデータをエクスポートして該当する箇所を特定し、ブラウザ上で保存する、という手順だと思います。

具体的には、管理メニューの`データアーカイブ > アーカイブデータの新規作成`にて、
 `MongoDB Page Collections` の `Pages`のみにチェックをいれてをエクスポートを実施、
生成されたファイルをダウンロードしてpages.jsonを開いてインデントし、
`"grantedUsers": null`をgrep

![image](https://github.com/user-attachments/assets/1a434379-1269-453b-a57d-f156a79ddf17)

これで該当のページを特定できるかと思います。

13個所くらいであれば手作業で対応したほうが速いでしょう。
`_id`や`path`を頼りに該当のページをブラウザで開いて保存することでgrantedUserdが`[]`(空配列)になると思います。

**Comment by kometchtech** [comment]
@soon624 さん
分かりやすい図解付きの手順でのご教授ありがとうございました。
無事に弊環境でもインデックスのリビルドが正常終了することが確認出来、問題を解消することが出来ました。

重ねてありがとうございました。
