### ISSUE TITLE
[7.1.2] Bug: Failed to retrieve AdminHome data

### ISSUE THREAD

**Issue by Triden99** [weseek/growi#9428]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 22.04.5|
|GROWI     |7.1.2|
|node.js   |version shipped with docker|
|npm       |version shipped with docker|
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]| yes |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        | Windows 10 |
|browser   |Firefox 132.0.1|

How to reproduce? (再現手順)
---------------------------

1. Upgrade from Growi 7.0.23 using docker upgrade instructions.
2. Go to http://wiki.domain.com/admin

```# go to growi-docker-compose workdir
cd growi

# stop
docker compose stop

# remove current container and images
docker compose rm app
docker rmi weseek/growi:7

# rebuild app container image
git pull
docker compose build

# start
docker compose up
```

What happens? (症状)
---------------------

- Info missing from main page (see image) and error pops up "Failed to retrive AdminHome data"

Thanks!

**Comment by Triden99** [comment]
Some relevant logs from docker compose
```
app-1  | {"name":"growi","hostname":"5fb2d5afe6a8","pid":1,"level":50,"msg":"Unhandled Rejection: Promise: Promise {\n  <rejected> TypeError: Cannot read properties of undefined (reading 'version')\n      at /opt/growi/apps/app/dist/server/routes/apiv3/admin-home.js:62:108\n      at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n      at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n      at /opt/growi/apps/app/dist/server/middlewares/admin-required.js:10:24\n      at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n      at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n      at /opt/growi/apps/app/dist/server/middlewares/login-required.js:20:24\n      at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n      at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n      at Route.dispatch (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:119:3)\n} Reason: TypeError: Cannot read properties of undefined (reading 'version')\n    at /opt/growi/apps/app/dist/server/routes/apiv3/admin-home.js:62:108\n    at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n    at /opt/growi/apps/app/dist/server/middlewares/admin-required.js:10:24\n    at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n    at /opt/growi/apps/app/dist/server/middlewares/login-required.js:20:24\n    at Layer.handle [as handle_request] (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/opt/growi/apps/app/node_modules/.pnpm/express@4.21.0/node_modules/express/lib/router/route.js:119:3)","time":"2024-11-20T21:38:50.184Z","v":0}
app-1  | {"name":"express","hostname":"5fb2d5afe6a8","pid":1,"req_id":"16bf6936-86da-4e7e-a1b8-a6523227a1b3","level":30,"msg":"::ffff:172.18.0.1 <-- GET /_next/data/CdH_1c7zxDWUAu0IIZodN/en_US.json HTTP/1.1 200 - https://wiki.sample.net/admin Firefox 132.0 Windows 10.0.0 31.160249 ms","time":"2024-11-20T21:38:51.035Z","v":0}
app-1  | {"name":"express","hostname":"5fb2d5afe6a8","pid":1,"req_id":"57687fe1-f8d0-46f4-bf6a-f10e1ebc2af4","level":30,"msg":"::ffff:172.18.0.1 <-- GET /_api/v3/admin-home/ HTTP/1.1 200 - https://wiki.sample.net/admin Firefox 132.0 Windows 10.0.0 99996.349437 ms","time":"2024-11-20T21:40:19.958Z","v":0}
app-1  | {"name":"express","hostname":"5fb2d5afe6a8","pid":1,"req_id":"7ea0e699-83c9-424b-8da3-a7ea39b24a16","level":30,"msg":"::ffff:172.18.0.1 <-- GET /_api/v3/admin-home/ HTTP/1.1 200 - https://wiki.sample.net/admin Firefox 132.0 Windows 10.0.0 100004.759365 ms","time":"2024-11-20T21:40:30.187Z","v":0}
```

**Comment by Triden99** [comment]
![image](https://github.com/user-attachments/assets/d925fff2-b5bc-4a29-a2f6-9de430a5588a)

**Comment by Triden99** [comment]
![image](https://github.com/user-attachments/assets/e03cdabe-a950-461b-8bc0-b5f29844c95f)

**Comment by yuki-takei** [comment]
Same with #9428. Please wait for the next version.
